flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/format_num.R
  - R/clean_username.R
  - R/export_list_to_word.R
  - R/create_summary_table.R
  - R/create_listing_table.R
  - R/clean_string.R
  - R/clean_phone_number.R
  - R/process_payroll.R
  - R/clean_camp.R
  - R/get_group_cols.R
  - R/check_esr_registrations.R
  - R/get_standard_villages.R
  - R/find_extra_agency_records.R
  - R/pull_kobo_data.R
  - R/clean_kobo_excel.R
  - R/cut_numeric.R
  - R/export_to_excel_formatted.R
  - R/export_to_excel_appended.R
  - R/get_duplicates.R
  - R/get_distinct.R
  - R/plot_bar.R
  - R/plot_bar_top_n.R
  - R/patchwork_grid.R
  - R/add_custom_total.R
  - R/collapse_villages.R
  - R/get_partial_matches.R
  - R/get_pii.R
  - R/write_list_to_excel.R
  - R/flatten_dm_by_names.R
  - R/preprocess_reg.R
  - R/preprocess.R
  - R/slice_reg.R
  - R/get_edit_data.R
  - R/draw_pps_sample.R
  - R/draw_pps_hamilton.R
  - R/draw_strs_sample.R
  - R/draw_cluster_sample.R
  - R/draw_systematic_across_villages.R
  - R/draw_systematic_within_villages.R
  - R/create_survey_object.R
  - R/apply_corrections.R
  - R/read_workbook.R
  - R/standardize_names.R
  - R/find_name_matches.R
  - R/match_county_records.R
  - R/normalize_names.R
  - R/gen_verification_criteria_table.R
  - R/get_vulnerability_data.R
  - R/automate_indicators.R
  - R/plot_parts_donut.R
  - R/plot_faceted_donuts.R
  - R/theme_plots.R
  - R/save_plots_to_png.R
  - R/plot_household_counts.R
  - R/plot_household_counts_interactive.R
  - R/get_partner_beneficiaries.R
  - R/calculate_disability_counts.R
  - R/recode_early_childhood_disability.R
  - R/recode_factor_to_character.R
  - R/get_dupes_with_name.R
  - R/label_kobo_columns.R
  - R/read_xlsform_asset.R
  - R/convert_excel_headers.R
  - R/label_with_xlsform.R
  - R/parse_hhsize.R
  - R/run_sample.R
  tests: tests/testthat/test-format_num.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_full.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
