# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

library(testthat)
library(officer)
library(gtsummary)
library(dplyr)
test_that("add_gt_to_word works correctly under different conditions", {
  
  # setup: create dummy data and a basic gtsummary object
  mock_df <- data.frame(
    status = c("active", "inactive", "active"),
    age = c(25, 34, 45)
  )
  mock_gt <- gtsummary::tbl_summary(mock_df, by = status)
  
  # test 1: verification of the standard portrait flow
  doc_portrait <- officer::read_docx()
  res_portrait <- add_gt_to_word(
    doc = doc_portrait, 
    gt_obj = mock_gt, 
    title = "Test Portrait Title", 
    landscape = FALSE
  )
  
  # check that an officer document object is returned
  expect_s3_class(res_portrait, "rdocx")
  
  # convert doc to content dataframe to check text insertion
  content_p <- officer::docx_summary(res_portrait)
  expect_true(any(content_p$text == "Test Portrait Title"))
  
  # test 2: verification of the landscape flow
  doc_landscape <- read_docx()
  res_landscape <- add_gt_to_word(
    doc = doc_landscape, 
    gt_obj = mock_gt, 
    title = "Test Landscape Title", 
    landscape = TRUE
  )
  
  expect_s3_class(res_landscape, "rdocx")
  
  content_l <- docx_summary(res_landscape)
  expect_true(any(content_l$text == "Test Landscape Title"))
  
  # test 3: safe verification of landscape structural layout differences
  # landscape structural blocks alter row structures or total summary elements
  expect_false(identical(nrow(content_p), nrow(content_l)))
})
