# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' calculate column-wise totals
#'
#' @param df dataframe
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{add_custom_total()}
add_custom_total <- function(df) {
  # calculate totals
  totals <- df %>%
    dplyr::summarise(
      Village = "Total",
      # only sum unique targeted values per village to avoid double counting
      `Targeted BNF` = base::sum(unique(`Targeted BNF`), na.rm = TRUE),
      `Registered BNF` = sum(`Registered BNF`, na.rm = TRUE),
      Variance = sum(Variance, na.rm = TRUE),
      `ESR Households` = sum(`ESR Households`, na.rm = TRUE),
      partner = NA
    )
  
  # combine with original data
  out <- bind_rows(df, totals)
  
  return(out)
}
