# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply Data Cleaning Corrections Using an Embedded Cleaning Log
#'
#' This function updates a main dataset using a correction data frame. It applies
#' standard cell corrections and handles row deletions last. Deletions are processed 
#' using strict unique UUID matching if a true uuid column is present, falling back to 
#' exact name matching combined with multiple context validation columns if a general 
#' non-unique identifier or name-only tracking is used.
#'
#' @param data A data frame containing the main dataset to be cleaned.
#' @param id_var The bare or quoted column name representing the unique identifier.
#' @param corrections A data frame containing the corrections log along with the matching keys.
#' @param var_to_change_col Column name in `corrections` holding target names to change.
#' @param correct_value_col Column name in `corrections` holding updated values.
#' @param ben_name_col Column name in both datasets holding beneficiary names.
#' @param context_cols Optional character vector. Secondary column names present in both 
#'   datasets (e.g., `c("ben_id_number", "ward", "village")`) used to build a composite key 
#'   and avoid accidental collisions of identical or similar names.
#'
#' @return A data frame matching the structure of `data`.
#' @export
apply_corrections <- function(
    data, 
    id_var = "uuid", 
    corrections, 
    var_to_change_col = "var_to_change", 
    correct_value_col = "correct_value",
    ben_name_col = "ben_name",
    context_cols = c("ben_id_number", "ward", "village")
) {
  
  id_str <- as.character(substitute(id_var))
  if (!id_str %in% names(data)) id_str <- id_var
  
  var_change_str <- as.character(substitute(var_to_change_col))
  if (!var_change_str %in% names(corrections)) var_change_str <- var_to_change_col
  
  correct_val_str <- as.character(substitute(correct_value_col))
  if (!correct_val_str %in% names(corrections)) correct_val_str <- correct_value_col
  
  ben_name_str <- as.character(substitute(ben_name_col))
  if (!ben_name_str %in% names(corrections)) ben_name_str <- ben_name_col
  
  cleaned_data <- data
  
  # extract only the unique variables that actually exist in the main data
  distinct_vars <- corrections %>%
    dplyr::filter(!!rlang::sym(var_change_str) %in% names(cleaned_data)) %>%
    dplyr::pull(!!rlang::sym(var_change_str)) %>%
    unique()
  
  # 1 execute standard cell corrections first
  for (current_var in distinct_vars) {
    sub_corrections <- corrections %>%
      dplyr::filter(!!rlang::sym(var_change_str) == current_var) %>%
      dplyr::select(dplyr::any_of(c(ben_name_str, correct_val_str)))
    
    target_class <- class(cleaned_data[[current_var]])[1]
    
    if (target_class %in% c("numeric", "integer")) {
      sub_corrections[[correct_val_str]] <- as.numeric(sub_corrections[[correct_val_str]])
    } else if (target_class == "logical") {
      sub_corrections[[correct_val_str]] <- as.logical(sub_corrections[[correct_val_str]])
    } else {
      sub_corrections[[correct_val_str]] <- as.character(sub_corrections[[correct_val_str]])
    }
    
    join_target_name <- paste0("new_val_", current_var)
    sub_corrections <- dplyr::rename(
      sub_corrections, 
      !!rlang::sym(join_target_name) := !!rlang::sym(correct_val_str)
    )
    
    cleaned_data <- cleaned_data %>%
      dplyr::left_join(sub_corrections, by = ben_name_str) %>%
      dplyr::mutate(
        !!rlang::sym(current_var) := ifelse(
          !is.na(!!rlang::sym(join_target_name)), 
          !!rlang::sym(join_target_name), 
          !!rlang::sym(current_var)
        )
      ) %>%
      dplyr::select(-dplyr::any_of(join_target_name))
  }
  
  # 2 handle deletions as the final operation with compound keys
  if (var_change_str %in% names(corrections) && ben_name_str %in% names(corrections) && ben_name_str %in% names(data)) {
    
    # filter log down strictly to the rows designated for deletion using case insensitive grepl
    delete_log <- corrections %>%
      dplyr::filter(grepl("delete", !!rlang::sym(var_change_str), ignore.case = TRUE))
    
    if (nrow(delete_log) > 0) {
      
      # premium bypass: only use direct ID deletion if it is explicitly a unique uuid column
      if (tolower(id_str) == "uuid" && id_str %in% names(corrections) && id_str %in% names(data)) {
        
        delete_ids <- delete_log %>%
          dplyr::pull(!!rlang::sym(id_str)) %>%
          unique()
        
        cleaned_data <- cleaned_data %>%
          dplyr::filter(!(!!rlang::sym(id_str) %in% delete_ids))
        
      } else {
        # traditional fallback: filter context columns down to only those that actually exist in both datasets
        # this ensures that if id_str is "ben_id_number", it gets lumped safely into the compound validation checks
        all_potential_contexts <- unique(c(id_str, context_cols))
        valid_contexts <- all_potential_contexts[all_potential_contexts %in% names(data) & all_potential_contexts %in% names(corrections)]
        
        if (length(valid_contexts) > 0) {
          # combine beneficiary name and all valid context values into a multi-variable string key
          # using individual rowwise evaluations to avoid vector collapse traps
          build_composite_key <- function(df, name_col, ctx_cols) {
            df %>%
              dplyr::rowwise() %>%
              dplyr::mutate(
                comp_key = paste(
                  c(as.character(.data[[name_col]]), mget(ctx_cols)), 
                  collapse = "|||"
                )
              ) %>%
              dplyr::ungroup() %>%
              dplyr::pull(comp_key)
          }
          
          # generate keys for both datasets
          delete_keys <- build_composite_key(delete_log, ben_name_str, valid_contexts)
          
          # apply filter by checking the main data against the delete keys
          cleaned_data <- cleaned_data %>%
            dplyr::rowwise() %>%
            dplyr::filter(
              !paste(c(as.character(.data[[ben_name_str]]), mget(valid_contexts)), collapse = "|||") %in% delete_keys
            ) %>%
            dplyr::ungroup()
          
        } else {
          # fallback to strict exact name checking if no valid context variables were matched
          delete_names <- unique(delete_log[[ben_name_str]])
          cleaned_data <- cleaned_data %>%
            dplyr::filter(!(!!rlang::sym(ben_name_str) %in% delete_names))
        }
      }
    }
  }
  
  return(cleaned_data)
}

