# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Automate binary indicator variable creation
#'
#' This function dynamically scans input columns, handles missing data structures,
#' cleans raw count variables, and generates binary 0/1 indicators based on 
#' underlying numeric and character type properties, preserving the original name.
#'
#' @param df A dataframe or tibble object.
#' @param cols A character vector specifying the target column names to process.
#'
#' @return A modified dataframe with updated raw counts and appended indicator columns.
#' @importFrom dplyr mutate across all_of if_else
#' @importFrom stringr str_detect
#' @export
automate_indicators <- function(df, cols) {
  df %>%
    # first pass clean all raw numeric count inputs to handle nas and zeros universally
    dplyr::mutate(
      dplyr::across(
        dplyr::all_of(cols),
        function(x) {
          # lower case comments without dots or dashes
          if (is.numeric(x)) {
            return(dplyr::if_else(is.na(x) | x == 0, 0, x))
          }
          return(x)
        }
      )
    ) %>%
    # second pass generate indicators and append ind cleanly to the original column names
    dplyr::mutate(
      dplyr::across(
        dplyr::all_of(cols), 
        function(x) {
          if (is.numeric(x)) {
            indicator <- dplyr::if_else(x == 0, 0, 1)
            return(indicator)
          } 
          
          # explicitly separate affirmative responses from negative or uncertain ones
          clean_x <- tolower(x)
          indicator <- dplyr::if_else(
            is.na(x) | 
              clean_x == "no" | 
              stringr::str_detect(clean_x, "not_at_all|not_really|dont_know|don't know"), 
            0, 
            1
          )
          return(indicator)
        }, 
        .names = "{.col}_ind"
      )
    )
}
