# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculate Psychological Distress Domain Disability Indicator
#'
#' Evaluates indicators for anxiety, depression, and a composite psychological
#' functional limitation flag using the Washington Group Enhanced Short Set scoring matrix.
#' The evaluation logic is case-insensitive to handle text rendering inconsistencies.
#'
#' @param data A data frame or tibble containing the survey responses.
#' @param anxiety_freq Character. The column name representing anxiety frequency
#'   (e.g., "Daily", "Weekly", "Never").
#' @param anxiety_intens Character. The column name representing anxiety intensity
#'   (e.g., "A lot", "A little").
#' @param depress_freq Character. The column name representing depression frequency.
#' @param depress_intens Character. The column name representing depression intensity.
#'
#' @return A data frame with three additional numeric columns:
#'   \item{has_anxiety}{Binary indicator (0 or 1) for anxiety limitation.}
#'   \item{has_depression}{Binary indicator (0 or 1) for depression limitation.}
#'   \item{has_disability_psych}{Composite binary indicator for the domain.}
#'   All indicators return \code{NA} if inputs contain non-responses like "Refused" or "Don't know".
#'
#' @importFrom dplyr mutate case_when sym select
#' @importFrom rlang !!
#' @export
#'
#' @examples
#' survey_responses <- tibble::tibble(
#'   dis_anxiety = c("Daily", "Weekly", "Never", "Refused"),
#'   dis_anxiety_frequency = c("A lot", "A little", "A little", "A lot"),
#'   dis_depression = c("Never", "Weekly", "Daily", "Don't know"),
#'   dis_anxiety_depression = c("A little", "A lot", "Somewhere in between", "A lot")
#' )
#'
#' processed_data <- calculate_psychological_distress(
#'   data = survey_responses,
#'   anxiety_freq = "dis_anxiety",
#'   anxiety_intens = "dis_anxiety_frequency",
#'   depress_freq = "dis_depression",
#'   depress_intens = "dis_anxiety_depression"
#' )
calculate_psychological_distress <- function(data, 
                                             anxiety_freq, 
                                             anxiety_intens, 
                                             depress_freq, 
                                             depress_intens) {
  # convert input column names to symbols for tidy evaluation
  # 
  af <- dplyr::sym(anxiety_freq)
  ai <- dplyr::sym(anxiety_intens)
  df <- dplyr::sym(depress_freq)
  di <- dplyr::sym(depress_intens)
  
  # track standard missing data labels
  # 
  missing_vals <- c("refused", "don't know", "don\u2019t know", NA_character_)
  
  data %>%
    dplyr::mutate(
      # normalize input strings to lowercase
      # 
      af_lower = tolower(!!af),
      ai_lower = tolower(!!ai),
      df_lower = tolower(!!df),
      di_lower = tolower(!!di),
      
      # score anxiety module
      # 
      has_anxiety = dplyr::case_when(
        (af_lower %in% missing_vals) | (ai_lower %in% missing_vals) ~ NA_real_,
        af_lower == "daily" & ai_lower %in% c("a lot", "somewhere in between a little and a lot") ~ 1,
        af_lower == "weekly" & ai_lower == "a lot" ~ 1,
        TRUE ~ 0
      ),
      
      # score depression module
      # 
      has_depression = dplyr::case_when(
        (df_lower %in% missing_vals) | (di_lower %in% missing_vals) ~ NA_real_,
        df_lower == "daily" & di_lower %in% c("a lot", "somewhere in between a little and a lot") ~ 1,
        df_lower == "weekly" & di_lower == "a lot" ~ 1,
        TRUE ~ 0
      ),
      
      # build composite indicator for psychological domain
      # 
      has_disability_psych = dplyr::case_when(
        is.na(has_anxiety) & is.na(has_depression) ~ NA_real_,
        has_anxiety == 1 | has_depression == 1 ~ 1,
        TRUE ~ 0
      )
    ) %>%
    # drop structural normalization variables
    # 
    dplyr::select(-c(af_lower, ai_lower, df_lower, di_lower))
}

#' validate and recode household disability flags based on repeat group ages
#'
#' @param df_out dataframe containing the main household data
#' @param df_disab dataframe containing the individual repeat group data
#' @param disab_col character matching pattern for the disability column. defaults to "HHM_disability"
#' @param uuid_col character string of the ID column name in df_out (defaults to "uuid")
#' @param age numeric lower age limit
#'
#' @returns an updated version of df_out with corrected disability flags
#'
#' @export
#'
#' @examples
#' # 
#' # create dummy main dataset
#' main_df <- data.frame(
#'   uuid = c("hh_1", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "yes", "no"),
#'   stringsAsFactors = FALSE
#' )
#'
#' # create dummy repeat group dataset
#' repeat_df <- data.frame(
#'   `uuid` = c("hh_1", "hh_1", "hh_2", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "no", "yes", "yes", "no"),
#'   prot_disability_ind_age = c(1, 35, 2, 1, 40),
#'   stringsAsFactors = FALSE,
#'   check.names = FALSE
#' )
#'
#' # run the function
#' output_df <- check_disability(main_df, repeat_df, disab_col = "HHM_disability", uuid_col = "uuid")
check_disability <- function(df_out, df_disab, disab_col = "HHM_disability", uuid_col = "uuid", age = 6) {
  
  # look up full matching column name inside target datasets
  # 
  matched_out_col <- grep(disab_col, names(df_out), value = TRUE, ignore.case = TRUE)[1]
  matched_disab_col <- grep(disab_col, names(df_disab), value = TRUE, ignore.case = TRUE)[1]
  
  # stop execution if the column match attempt returns empty fields
  if (is.na(matched_out_col) || is.na(matched_disab_col)) {
    stop(sprintf("could not find a matching column for '%s' in data frames", disab_col))
  }
  
  disab_sym_out <- rlang::ensym(matched_out_col)
  disab_sym_disab <- rlang::ensym(matched_disab_col)
  
  # step 1 isolate active disability rows and find the maximum age per household
  hh_max_disab_age <- df_disab %>%
    dplyr::filter(stringr::str_detect(tolower(!!disab_sym_disab), "yes")) %>%
    dplyr::group_by(.data[[uuid_col]]) %>%
    dplyr::summarise(
      max_age = max(prot_disability_ind_age, na.rm = TRUE),
      .groups = "drop"
    )
  
  # step 2 extract household IDs where the maximum disabled age is below threshold
  infant_only_uuids <- hh_max_disab_age %>%
    dplyr::filter(max_age < age) %>%
    dplyr::pull(.data[[uuid_col]])
  
  # step 3 calculate diagnostics for console visibility
  total_infant_only_hh <- length(infant_only_uuids)
  
  # step 4 recode the main dataset if any invalid target households exist
  df_out_updated <- df_out %>%
    dplyr::mutate(
      !!disab_sym_out := dplyr::if_else(
        .data[[uuid_col]] %in% infant_only_uuids,
        "no",
        !!disab_sym_out
      )
    )
  
  # step 5 print diagnostic feedback to the console safely
  message("--- disability check summary ---")
  message(sprintf("households with active disability loops: %d", nrow(hh_max_disab_age)))
  message(sprintf("households where all disabled members are < %d (total: %d)", age, total_infant_only_hh))
  
  if (total_infant_only_hh > 0) {
    message("action: invalid household flags successfully recoded to 'no'")
  } else {
    message("action: no adjustments needed, all household flags are structurally valid")
  }
  message("--------------------------------")
  
  return(df_out_updated)
}
