# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' calculate a row level individual disability indicator
#'
#' @param data dataframe containing the individual disability columns
#' @param disability_cols character vector of column names representing the domains
#'
#' @returns an integer vector of 1s and 0s indicating if the individual has any disability
#' @export
calculate_disability_counts <- function(data, 
                                        disability_cols = c(
                                          "level_seeing_disability",
                                          "level_hearing_disability",
                                          "level_selfcare_disability",
                                          "level_remembering_disability",
                                          "level_walking_disability",
                                          "level_communicating_disability"
                                        )) {
  
  # extract target columns to safely check row conditions
  subset_matrix <- data %>% 
    dplyr::select(dplyr::any_of(disability_cols))
  
  # match case-insensitively against the exact literal strings provided
  # lower case comments without dots
  match_matrix <- base::apply(subset_matrix, 2, function(col) {
    stringr::str_to_lower(base::as.character(col)) %in% c("some difficulty", "a lot of difficulty", "cannot do at all")
  })
  
  # collapse individual domains down to a single binary indicator per row
  dplyr::if_else(base::rowSums(match_matrix, na.rm = TRUE) > 0, 1L, 0L)
}

