# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' calculate the total number of disabled individuals at the household level
#'
#' @param data dataframe containing the individual disability columns and a household identifier
#' @param hh_id_col character name of the column storing the unique household id
#' @param disability_cols character vector of column names representing the domains
#'
#' @returns an integer vector representing the total disabled household members for each row
#' @export
calculate_hh_disability_counts <- function(data, 
                                           hh_id_col = "uuid",
                                           disability_cols = c(
                                             "level_seeing_disability",
                                             "level_hearing_disability",
                                             "level_selfcare_disability",
                                             "level_remembering_disability",
                                             "level_walking_disability",
                                             "level_communicating_disability"
                                           )) {
  
  # extract target columns to safely check row conditions
  subset_matrix <- data %>% 
    dplyr::select(dplyr::any_of(disability_cols))
  
  # match case-insensitively against the exact literal choices provided
  # lower case comments without dots
  match_matrix <- base::apply(subset_matrix, 2, function(col) {
    stringr::str_to_lower(base::as.character(col)) %in% c("some difficulty", "a lot of difficulty", "cannot do at all")
  })
  
  # collapse individual domains down to a single binary indicator per row
  ind_disabled <- dplyr::if_else(base::rowSums(match_matrix, na.rm = TRUE) > 0, 1L, 0L)
  
  # create a temporary tracking block to calculate the broadcasted household sums safely
  result_vector <- data %>%
    dplyr::mutate(temp_ind_disabled = ind_disabled) %>%
    dplyr::group_by(.data[[hh_id_col]]) %>%
    dplyr::mutate(total_disabled_in_hh = base::sum(temp_ind_disabled, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::pull(total_disabled_in_hh)
  
  return(result_vector)
}
