# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' calculate total disability counts vector
#'
#' @param data dataframe containing the disability columns
#' @param disability_cols character vector of column names representing the domains
#'
#' @returns an integer vector containing the sum of matching disabilities per row
#' @export
calculate_disability_counts <- function(data, 
                                        disability_cols = c(
                                          "level_seeing_disability",
                                          "level_hearing_disability",
                                          "level_selfcare_disability",
                                          "level_remembering_disability",
                                          "level_walking_disability",
                                          "level_communicating_disability"
                                        )) {
  
  # extract just the target columns to evaluate row sums
  subset_matrix <- data %>% 
    dplyr::select(dplyr::all_of(disability_cols))
  
  # check for the target difficulty strings using a regular expression pattern
  match_matrix <- base::apply(subset_matrix, 2, function(col) {
    base::grepl("difficulty|at all", base::as.character(col), ignore.case = TRUE)
  })
  
  # sum the matching occurrences row-by-row and return the integer vector
  base::rowSums(match_matrix, na.rm = TRUE)
}
