# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' calculate household hunger score and categorical scale
#'
#' @param data dataframe containing the food security survey responses
#' @param nofood_col character matching pattern for no food in house column
#' @param nofood_fr_col character matching pattern for frequency of no food
#' @param noteat_col character matching pattern for went to sleep hungry column
#' @param noteat_fr_col character matching pattern for frequency of went to sleep hungry
#' @param bedhung_col character matching pattern for went 24 hours without eating column
#' @param bedhung_fr_col character matching pattern for frequency of 24 hours without eating
#'
#' @returns an updated dataframe with columns 'hhs_score' and 'hhs_categorical'
#' @export
#'
#' @examples
#' # 
#' # create dummy dataset
#' survey_df <- data.frame(
#'   hhsnofood = c("yes", "no", "yes"),
#'   hhsnofood_fr = c("sometimes", NA, "often"),
#'   hhsnoteat = c("no", "yes", "yes"),
#'   hhsnoteat_fr = c(NA, "rarely", "often"),
#'   hhsbedhung = c("no", "no", "yes"),
#'   hhsbedhung_fr = c(NA, NA, "sometimes"),
#'   stringsAsFactors = FALSE
#' )
#'
#' hhs_results <- calculate_hunger_score(survey_df)
calculate_hunger_score <- function(data,
                          nofood_col = "hhsnofood",
                          nofood_fr_col = "hhsnofood_fr",
                          noteat_col = "hhsnoteat",
                          noteat_fr_col = "hhsnoteat_fr",
                          bedhung_col = "hhsbedhung",
                          bedhung_fr_col = "hhsbedhung_fr") {
  
  # helper function to locate column names using case-insensitive grep matches
  # lower case comments without dots
  find_col <- function(pattern, df) {
    matched <- base::grep(pattern, base::names(df), value = TRUE, ignore.case = TRUE)[1]
    if (base::is.na(matched)) {
      base::stop(base::sprintf("could not find a matching column for pattern: '%s'", pattern))
    }
    return(matched)
  }
  
  # map raw target column labels dynamically
  c_nofood    <- find_col(nofood_col, data)
  c_nofood_fr <- find_col(nofood_fr_col, data)
  c_noteat    <- find_col(noteat_col, data)
  c_noteat_fr <- find_col(noteat_fr_col, data)
  c_bedhung   <- find_col(bedhung_col, data)
  c_bedhung_fr <- find_col(bedhung_fr_col, data)
  
  # internal score engine for each sub-domain logic block
  # maps rarely to 1, sometimes to 2, and often to 3
  score_domain <- function(indicator, frequency) {
    ind_clean <- base::tolower(base::as.character(indicator))
    fr_clean  <- base::tolower(base::as.character(frequency))
    
    # default to 0 if the condition did not occur
    if (base::is.na(ind_clean) || ind_clean != "yes") {
      return(0L)
    }
    
    # decode frequency paths explicitly
    score <- base::switch(fr_clean,
                          "rarely"    = 1L,
                          "sometimes" = 2L,
                          "often"     = 3L,
                          0L)
    return(score)
  }
  
  # execute vectorized computation row by row across matrix layouts
  scores <- base::vapply(1:base::nrow(data), function(i) {
    s1 <- score_domain(data[i, c_nofood], data[i, c_nofood_fr])
    s2 <- score_domain(data[i, c_noteat], data[i, c_noteat_fr])
    s3 <- score_domain(data[i, c_bedhung], data[i, c_bedhung_fr])
    return(s1 + s2 + s3)
  }, integer(1))
  
  # classify categorical hunger definitions based on aggregated limits
  categories <- base::ifelse(scores <= 1, "Little to no hunger",
                             base::ifelse(scores <= 3, "Moderate hunger", "Severe hunger"))
  
  # append structured calculations cleanly back into data frame output
  data$hhs_score <- scores
  data$hhs_categorical <- categories
  
  return(data)
}
