# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' validate and recode household disability flags based on repeat group ages in a single dataset
#'
#' @param data dataframe containing both household markers and individual repeat rows
#' @param disab_col character matching pattern for the disability column name to validate and update
#' @param uuid_col character string of the ID column name (defaults to "uuid")
#' @param age numeric lower age limit
#'
#' @returns an updated version of the dataframe with corrected disability flags
#'
#' @export
#'
#' @examples
#' # lower case comments without dots or dashes
#' # create dummy joined dataset
#' survey_data <- data.frame(
#'   uuid = c("hh_1", "hh_1", "hh_2", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "yes", "yes", "yes", "no"),
#'   prot_disability_ind_age = c(1, 35, 2, 1, 40),
#'   stringsAsFactors = FALSE,
#'   check.names = FALSE
#' )
#'
#' # run the function
#' output_df <- check_disability_single(survey_data, disab_col = "HHM_disability", uuid_col = "uuid")
check_disability_single <- function(data, disab_col, uuid_col = "uuid", age = 6) {
  
  # look up matching column name inside the dataframe
  # lower case comments without dots or dashes
  matched_col <- grep(disab_col, names(data), value = TRUE, ignore.case = TRUE)[1]
  
  # stop execution if no match is found
  if (is.na(matched_col)) {
    stop(sprintf("could not find a matching column for '%s' in the dataframe", disab_col))
  }
  
  disab_sym <- rlang::ensym(matched_col)
  
  # step 1 isolate active disability rows and find the maximum age per household
  hh_max_disab_age <- data %>%
    dplyr::filter(stringr::str_detect(tolower(!!disab_sym), "yes")) %>%
    dplyr::group_by(.data[[uuid_col]]) %>%
    dplyr::summarise(
      max_age = max(prot_disability_ind_age, na.rm = TRUE),
      .groups = "drop"
    )
  
  # step 2 extract household IDs where the maximum disabled age is below threshold
  infant_only_uuids <- hh_max_disab_age %>%
    dplyr::filter(max_age < age) %>%
    dplyr::pull(.data[[uuid_col]])
  
  # step 3 calculate diagnostics for console visibility
  total_infant_only_hh <- length(infant_only_uuids)
  
  # step 4 recode target household rows within the single dataframe
  data_updated <- data %>%
    dplyr::mutate(
      !!disab_sym := dplyr::if_else(
        .data[[uuid_col]] %in% infant_only_uuids,
        "no",
        !!disab_sym
      )
    )
  
  # step 5 print diagnostic feedback to the console safely
  message("--- disability check summary ---")
  message(sprintf("households with active disability loops: %d", nrow(hh_max_disab_age)))
  message(sprintf("households where all disabled members are < %d (total: %d)", age, total_infant_only_hh))
  
  if (total_infant_only_hh > 0) {
    message("action: invalid household flags successfully recoded to 'no'")
  } else {
    message("action: no adjustments needed, all household flags are structurally valid")
  }
  message("--------------------------------")
  
  return(data_updated)
}
