# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

# registrations appearing in ESR
#' Title
#'
#' @param data1 dataframe. registration data
#' @param data2 dataframe. ESR data
#'
#' @returns a dataframe
#' @export
#'
#' @examples
#' \dontrun{check_esr_registrations(data1 = df_clean, data2 = df_esr)}
check_esr_registrations <- function(data1 = df_clean, data2 = df_esr) {

  
  # 1. prepare lookup keys from data2
  # combine names and clean id and phone for matching
  data2_prepared <- data2 %>%
    dplyr::mutate(
      full_name_clean = clean_string(paste(first_name, middle_name, last_name)),
      first_surname = clean_string(paste(first_name, last_name)),
      first_secname = clean_string(paste(first_name, middle_name)),
      id_clean        = clean_string(id_number1),
      phone_clean     = clean_string(phone_number)
    )
  
  lookup_ids    <- unique(data2_prepared$id_clean)
  lookup_names  <- unique(data2_prepared$full_name_clean)
  lookup_names1  <- unique(data2_prepared$first_surname)
  lookup_names2  <- unique(data2_prepared$first_secname)
  lookup_phones <- unique(data2_prepared$phone_clean)
  
  # 2. apply matching logic to data1
  data1 %>%
    dplyr::mutate(
      is_in_second_dataset = case_when(
        # check by id number
        clean_string(ben_id_number) %in% lookup_ids ~ "yes",
        
        # check by phone number using reg_num_phone
        clean_string(reg_num_phone) %in% lookup_phones ~ "yes",
        
        # check by combined name
        clean_string(ben_name) %in% lookup_names ~ "yes",
        clean_string(ben_first_surname) %in% lookup_names1 ~ "yes",
        clean_string(ben_first_secname) %in% lookup_names2 ~ "yes",
        
        # default to no if no matches are found
        TRUE ~ "no"
      )
    )
}
