# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean recode beneficiary camp 
#'
#' @param x dataframe
#' @param col_name character column with camp names, defaults to 'ben_camp'
#' @param partner_col character column with partner organization names, defaults to 'reforgp'
#'
#' @returns dataframe
#' @importFrom dplyr case_when all_of across
#' @export
#'
#' @examples
#' \dontrun{clean_camp(x, col_name = "ben_camp", partner_col = "reforgp")}
clean_camp <- function(x, col_name = "ben_camp", partner_col = "reforgp") {
  x %>% 
    dplyr::mutate(
      dplyr::across(dplyr::all_of(col_name), ~ dplyr::case_when(
        # use the .data pronoun to dynamically evaluate the partner column name input
        grepl("\\bna\\b|N/A|kawangware|kayole|kasarani|kangemi|kikuyu|home", .x, ignore.case = TRUE) & grepl("HIAS", .data[[partner_col]], ignore.case = TRUE) ~ "Nairobi",
        grepl("^k|^rece", .x, ignore.case = TRUE) ~ "Kakuma",
        grepl("^nai|east|urban|umoja|rongai|settl", .x, ignore.case = TRUE) ~ "Nairobi",
        grepl("^daga|ley$|^ifo|f0|fo|^haga|^v|dad|daad", .x, ignore.case = TRUE) ~ "Daadab",
        is.na(.x) ~ "Nairobi",
        TRUE ~ .x
      ))
    )
}
