# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

# clean string

#' clean string of spaces and non alphanumeric characters and make lower case
#'
#' @param x a vector of characters
#'
#' @returns a vector
#' @export
#'
#' @examples
#' \dontrun{clean_String('Nachola124')}


clean_string <- function(x) {
  x %>%
    as.character() %>%
    stringr::str_to_lower() %>%
    stringr::str_replace_all("[^a-z0-9]", "") %>%
    stringr::str_trim()
}
