# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Clean names by deleting extra spaces and convert to title case
#'
#' @param x character vector of names to clean
#'
#' @returns a vector
#' @export
#'
#' @examples
#' \dontrun{clean_username()}
clean_username <- function(x){
  x %>% stringr::str_to_title(stringr::str_squish(.))
}
