# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

# clean ben_camp

#' clean recode beneficiary camp 
#'
#' @param x dataframe
#' @param col_name  character. column with camp names
#'
#' @returns dataframe
#' @importFrom dplyr case_when all_of across
#' @export
#'
#' @examples
#' \dontrun{clean_camp(x, col_name = "ben_camp")}
clean_camp <- function(x, col_name = "ben_camp"){
  x  %>% 
    dplyr::mutate(
      across(all_of(col_name), ~ case_when(
        # use stringr or grepl with the .x pronoun
        grepl("\\bna\\b", .x, ignore.case = TRUE) & grepl("HIAS", reforgp, ignore.case = T) ~ "Nairobi",
        grepl("^k", .x, ignore.case = TRUE) ~ "Kakuma",
        grepl("^nai|east|urban|umoja", .x, ignore.case = TRUE) ~ "Nairobi",
        grepl("^daga|ley$|^ifo|f0|fo|^haga|^v|dad|daad", .x, ignore.case = TRUE) ~ "Daadab",
        TRUE ~ .x
      ))
    )
}
