# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean names by removing special characters, deleting extra spaces, and converting to title case
#'
#' @param x character vector of names to clean
#'
#' @returns a vector
#' @export
#'
#' @examples
#' \dontrun{clean_username()}
clean_username <- function(x) {
  x %>%
    # remove all special characters like brackets, braces, and punctuation
    stringr::str_remove_all("[^[:alnum:][:space:]]") %>%
    # collapse duplicate whitespace down to single spaces
    stringr::str_squish() %>%
    # convert the cleaned text string to title case format
    stringr::str_to_title()
}
