# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean manual kobo excel data to align with api structure
#'
#' @param data data.frame. the raw excel data frame (ddd)
#'
#' @returns a cleaned data frame matching the transformed api structure
#' @export
#'
#' @examples
#' \dontrun{clean_kobo_excel(ddd)}
clean_kobo_excel <- function(data) {
  
  if (!is.data.frame(data)) {
    stop("input must be a data frame")
  }
  
  # 1. remove trailing or leading white spaces from character columns
  cleaned_df <- data %>%
    dplyr::mutate(dplyr::across(dplyr::where(is.character), stringr::str_trim))
  
  # 2. handle potential duplicate columns before renaming
  # if both "middle_name" and "ben_reff" exist, drop the plain "ben_reff" to avoid a collision
  if ("middle_name" %in% names(cleaned_df) && "ben_reff" %in% names(cleaned_df)) {
    cleaned_df <- cleaned_df %>% dplyr::select(-dplyr::any_of("ben_reff"))
  }
  
  # 3. handle structural header renames to match code/value naming layout
  cleaned_df <- cleaned_df %>%
    dplyr::rename(
      # map core name metadata variations
      ben_first = dplyr::any_of("first_name"),
      ben_reff = dplyr::any_of("middle_name"),
      benf_last = dplyr::any_of("last_name"),
      data_entry_name = dplyr::any_of("name_of_person_collecting_information"),
      cordinates = dplyr::any_of("please_collect_the_beneficiary_gps_coordinates"),
      
      # convert exploded select_multiple text fields to match api value strings
      livelihood_source_dnk = dplyr::any_of("livelihood_source_dont_know"),
      livelihood_source_f_employment = dplyr::any_of("livelihood_source_formal_employment"),
      livelihood_source_frm_lvstk = dplyr::any_of("livelihood_source_farming_livestock"),
      livelihood_source_other_benflivelihood = dplyr::any_of("livelihood_source_other"),
      livelihood_source_ss_business = dplyr::any_of("livelihood_source_small_scale_business")
    )
  
  # 4. safely drop internal coordinate splits and extra tracker tags 
  cleaned_df <- cleaned_df %>%
    dplyr::select(
      -dplyr::any_of(c(
        "cordinates_latitude",
        "cordinates_longitude",
        "cordinates_altitude",
        "cordinates_precision",
        "please_collect_the_beneficiary_gps_coordinates_latitude",
        "please_collect_the_beneficiary_gps_coordinates_longitude",
        "please_collect_the_beneficiary_gps_coordinates_altitude",
        "please_collect_the_beneficiary_gps_coordinates_precision",
        "index",
        "tags",
        "notes"
      ))
    )
  
  # 5. ensure placeholder columns exist if they are present in df_lab structure
  if ("ben_reff" %in% names(cleaned_df) && !("benf_sec" %in% names(cleaned_df))) {
    cleaned_df <- cleaned_df %>% dplyr::rename(benf_sec = ben_reff)
  }
  
  if (!"ref_priority" %in% names(cleaned_df)) {
    cleaned_df$ref_priority <- NA_character_
  }
  
  return(cleaned_df)
}
