# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' collapse villages that share targets, separating by /
#'
#' @param df dataframe
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{collapse_villages()}
collapse_villages <- function(df) {
  df_collapsed <- df %>%
    # group by the columns where you want to identify duplicates
    dplyr::group_by(`Targeted BNF`, `ESR Households`, partner) %>%
    dplyr::summarise(
      # collapse village names with a slash
      village = paste(unique(village), collapse = " / "),
      # sum the registered beneficiaries
      `Registered BNF` = sum(`Registered BNF`, na.rm = TRUE),
      # keep the group order clean
      .groups = "drop"
    ) %>%
    # relocate columns to match your original structure
    dplyr::select(village, `Targeted BNF`, `ESR Households`, partner, `Registered BNF`)
  
  return(df_collapsed)
}
