# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' convert labeled excel headers to kobo code/value headers using form schema
#'
#' @param target_df data.frame. the raw excel data frame with text headers (df)
#' @param project_id character. kobo project uid
#' @param url character. Kobotoolbox url
#' @param token character. project token
#'
#' @returns a data frame with clean value headers matching df_lab
#' @export
convert_excel_headers <- function(
    target_df,
    url = Sys.getenv("kobo_url2"),
    project_id = Sys.getenv("mpca_id"),
    token = Sys.getenv("kobo_token")
) {
  
  # 1. pull the asset form schema from the api
  robotoolbox::kobo_setup(url = url, token = token)
  asset <- robotoolbox::kobo_asset(project_id)
  form_schema <- robotoolbox::kobo_form(asset)
  
  # 2. isolate question row rows with non-empty names and labels
  # clean the labels exactly how R cleans column names upon import
  mapping_dict <- form_schema %>%
    dplyr::filter(!is.na(name), !is.na(label)) %>%
    dplyr::mutate(
      clean_label = janitor::make_clean_names(label)
    ) %>%
    dplyr::select(clean_label, name) %>%
    dplyr::distinct(clean_label, .keep_all = TRUE) %>%
    tibble::deframe() # turns it into a named vector: c(clean_label = "name")
  
  # 3. safely handle complex select_multiple columns
  # kobo appends choice suffixes to the question stem for binary choice columns
  # e.g., 'what_is_the_current_source_of_livelihood..._formal_employment' -> 'livelihood_source_f_employment'
  current_names <- names(target_df)
  new_names <- sapply(current_names, function(col_name) {
    
    # direct hit check against standard questions
    if (col_name %in% names(mapping_dict)) {
      return(mapping_dict[[col_name]])
    }
    
    # check if this column is a split choice from a select_multiple question block
    # matches the longest matching stem and finds the underlying code value
    matches <- sapply(names(mapping_dict), function(lbl) stringr::str_starts(col_name, fixed(lbl)))
    if (any(matches)) {
      best_fit_lbl <- names(which(matches))[which.max(nchar(names(which(matches))))]
      base_code_name <- mapping_dict[[best_fit_lbl]]
      
      # extract just the choice suffix appended to the end of the text label
      suffix <- stringr::str_remove(col_name, paste0("^", regexp_quote(best_fit_lbl), "_?"))
      
      # reconstruct the backend column name string structure
      return(paste0(base_code_name, "_", suffix))
    }
    
    # return original name if no match found (e.g. metadata markers like uuid, start, end)
    return(col_name)
  })
  
  # 4. assign the translated backend names onto your excel dataset
  names(target_df) <- unname(new_names)
  
  # 5. a quick universal adjustment pass for project-agnostic group paths
  # fixes remnants of section wrappers if your schema lists them cleanly
  target_df <- target_df %>%
    dplyr::rename_with(~ stringr::str_replace_all(.x, "\\.", "_"))
  
  return(target_df)
}

# helper function to escape characters for safe regex evaluation
regexp_quote <- function(kv) {
  gsub("([.[{}()^*+?|\\^$])", "\\\\\\1", kv)
}
