# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' create a survey design object dynamically for any complex sampling design
#'
#' @param sample_df dataframe containing the final selected sample observations
#' @param population_df dataframe containing the full original population sampling frame
#' @param id_cols character vector identifying structural cluster nodes in cascading order (e.g., c("village", "hh_id"))
#' @param strata_cols character vector containing names of stratification columns (optional, defaults to NULL)
#' @param weight_col_name character string naming the output column for calculated weights
#'
#' @returns a configured survey design object
#' @export
create_survey_object <- function(sample_df, 
                                        population_df, 
                                        id_cols, 
                                        strata_cols = NULL, 
                                        weight_col_name = "sampling_weight") {
  
  # ensure package namespace dependencies are available
  if (!requireNamespace("survey", quietly = TRUE)) {
    stop("the 'survey' package is required but not installed")
  }
  
  # handle missing variable safety up front
  all_vars <- unique(c(id_cols, strata_cols))
  missing_sample <- all_vars[!all_vars %in% names(sample_df)]
  missing_pop    <- all_vars[!all_vars %in% names(population_df)]
  
  if (length(missing_sample) > 0 || length(missing_pop) > 0) {
    stop("specified structural columns missing from sample or population dataframes")
  }
  
  # step 1: isolate stage 1 units (primary sampling units) to evaluate selection probabilities
  psu_col <- id_cols[1]
  stage1_grouping <- unique(c(strata_cols, psu_col))
  
  pop_psus <- population_df %>%
    dplyr::distinct(dplyr::across(dplyr::all_of(stage1_grouping))) %>%
    dplyr::count(dplyr::across(dplyr::all_of(strata_cols)), name = "..total_PSUs_in_strata..")
  
  sample_psus <- sample_df %>%
    dplyr::distinct(dplyr::across(dplyr::all_of(stage1_grouping))) %>%
    dplyr::count(dplyr::across(dplyr::all_of(strata_cols)), name = "..sampled_PSUs_in_strata..")
  
  # map stage 1 probability across rows
  stage1_probs <- population_df %>%
    dplyr::distinct(dplyr::across(dplyr::all_of(stage1_grouping))) %>%
    dplyr::left_join(pop_psus, by = strata_cols) %>%
    dplyr::left_join(sample_psus, by = strata_cols) %>%
    # if unstratified, handle empty grouping count variables safely
    dplyr::mutate(
      ..total_PSUs_in_strata..   = ifelse(is.na(..total_PSUs_in_strata..), length(unique(population_df[[psu_col]])), ..total_PSUs_in_strata..),
      ..sampled_PSUs_in_strata.. = ifelse(is.na(..sampled_PSUs_in_strata..), length(unique(sample_df[[psu_col]])), ..sampled_PSUs_in_strata..),
      ..prob_stage1..            = ..sampled_PSUs_in_strata.. / ..total_PSUs_in_strata..
    ) %>%
    dplyr::select(dplyr::all_of(stage1_grouping), "..prob_stage1..")
  
  # step 2: evaluate stage 2 units (secondary sampling units) if a second id column is specified
  if (length(id_cols) > 1) {
    ssu_grouping <- unique(c(strata_cols, id_cols[1:2]))
    
    pop_ssus <- population_df %>%
      dplyr::count(dplyr::across(dplyr::all_of(id_cols[1])), name = "..total_SSUs_in_PSU..")
    
    sample_ssus <- sample_df %>%
      dplyr::count(dplyr::across(dplyr::all_of(id_cols[1])), name = "..sampled_SSUs_in_PSU..")
    
    stage2_probs <- pop_ssus %>%
      dplyr::left_join(sample_ssus, by = id_cols[1]) %>%
      dplyr::mutate(
        ..sampled_SSUs_in_PSU.. = ifelse(is.na(..sampled_SSUs_in_PSU..), 0, ..sampled_SSUs_in_PSU..),
        ..prob_stage2..         = ..sampled_SSUs_in_PSU.. / ..total_SSUs_in_PSU..
      ) %>%
      dplyr::select(dplyr::all_of(id_cols[1]), "..prob_stage2..")
    
    # join stage 1 and stage 2 tracks together to compute joint weights
    final_weights <- stage1_probs %>%
      dplyr::inner_join(stage2_probs, by = id_cols[1]) %>%
      dplyr::mutate(
        !!weight_col_name := 1 / (..prob_stage1.. * ..prob_stage2..)
      ) %>%
      dplyr::select(dplyr::all_of(c(id_cols[1], weight_col_name)))
    
  } else {
    # single stage designs pass flat inverse probability configurations down stream
    final_weights <- stage1_probs %>%
      dplyr::mutate(
        !!weight_col_name := 1 / ..prob_stage1..
      ) %>%
      dplyr::select(dplyr::all_of(c(stage1_grouping, weight_col_name)))
  }
  
  # step 3: combine finalized weights lookup to sample frame and create svydesign object
  sample_with_weights <- sample_df %>%
    dplyr::inner_join(final_weights, by = id_cols[1])
  
  id_formula     <- stats::as.formula(paste0("~", paste(id_cols, collapse = " + ")))
  strata_formula <- if (!is.null(strata_cols)) stats::as.formula(paste0("~", paste(strata_cols, collapse = " + "))) else NULL
  weight_formula <- stats::as.formula(paste0("~", weight_col_name))
  
  survey_obj <- survey::svydesign(
    ids = id_formula,
    strata = strata_formula,
    weights = weight_formula,
    data = sample_with_weights
  )
  
  return(survey_obj)
}
