# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.


#' create `gtreg` table listing of data
#'
#' @param data dataframe
#' @param cols columns to include
#' @param labels character. labels
#' @param group_by character. grouping variable 
#'
#' @returns a list
#' @export
#'
#' @examples
#'\dontrun{create_listing_table()}
create_listing_table <- function(data,
                                 cols = dplyr::everything(),
                                 labels = list(),
                                 group_by = NULL) {
  data %>%
    {
      if (!is.null(group_by))
        dplyr::arrange(., .data[[group_by]])
      else
        .
    } %>%
    dplyr::select({{ cols }}, dplyr::any_of(group_by)) %>%
    gtreg::tbl_listing() %>%
    gtsummary::bold_labels()
}

