# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' create a `gtsummary` table
#'
#' @param data dataframe
#' @param cols columns to include
#' @param labels character. labels
#' @param group_by character. grouping variable
#' @param strata character. stratifying variable
#' @param percent_type character. percents by row or column
#'
#' @returns a list of gtsummary object 
#' @export
#'
#' @examples
#'\dontrun{create_summary_table()}
create_summary_table <- function(data, 
                                 cols = dplyr::everything(), 
                                 labels = list(), 
                                 group_by = NULL,
                                 strata = NULL,
                                 percent_type = "column") {
  
  
  # internal helper to build the base table
  build_summary <- function(df) {
    df %>%
      # any_of(group_by) handles the case where group_by might be null
      dplyr::select({{cols}}, dplyr::any_of(group_by)) %>%
      gtsummary::tbl_summary(
        by = dplyr::any_of(group_by),
        label = labels,
        percent = percent_type,
        type = list(all_categorical() ~ "categorical"),
        statistic = list(
          all_continuous() ~ "{mean} ({median})",
          all_categorical() ~ "{n} ({p}%)"
        ),
        digits = list(
          all_continuous() ~ purrr::partial(style_number, big.mark = ","),
          all_categorical() ~ c(0, 1)
        ),
        missing = "no"
      ) %>%
      gtsummary::add_n() %>%
      gtsummary::bold_labels()
  }
  
  # logic to handle stratification
  if (!is.null(strata)) {
    data %>%
      # ensure the strata column exists before passing to tbl_strata
      gtsummary::tbl_strata(
        strata = all_of(strata),
        .tbl_fun = ~ build_summary(.x)
      )
  } else {
    build_summary(data)
  }
}
