# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' create a `gtsummary` table
#'
#' @param data dataframe
#' @param cols columns to include
#' @param labels character. labels
#' @param group_by character. grouping variable
#' @param strata character. stratifying variable
#' @param percent_type character. percents by row or column
#' @param dichotomous_as_continuous logical. treat binary 0/1 columns as continuous
#' @param report_median logical. whether to include the median alongside the mean for continuous variables
#' @param label_characteristic character. custom header text for the characteristic column
#'
#' @returns a flextable object 
#' @export
create_summary_table <- function(data, 
                                 cols = dplyr::everything(), 
                                 labels = list(), 
                                 group_by = NULL,
                                 strata = NULL,
                                 percent_type = "column",
                                 dichotomous_as_continuous = FALSE,
                                 report_median = FALSE,
                                 label_characteristic = "Characteristic") {
  
  # internal helper to build the base table
  build_summary <- function(df) {
    # build the type list dynamically based on the parameter
    summary_types <- list(all_categorical() ~ "categorical")
    if (dichotomous_as_continuous) {
      summary_types <- c(summary_types, list(gtsummary::all_dichotomous() ~ "continuous"))
    }
    
    # dynamically adjust the statistic block based on report_median flag
    continuous_stat <- if (report_median) "{mean} ({median})" else "{mean}"
    
    df %>%
      # any_of(group_by) handles the case where group_by might be null
      dplyr::select({{cols}}, dplyr::any_of(group_by)) %>%
      gtsummary::tbl_summary(
        by = dplyr::any_of(group_by),
        label = labels,
        percent = percent_type,
        type = summary_types,
        statistic = list(
          all_continuous() ~ continuous_stat,
          all_categorical() ~ "{n} ({p}%)"
        ),
        digits = list(
          # convert continuous proportions to whole numbers and append percentage sign
          all_continuous() ~ function(x) paste0(gtsummary::style_number(x * 100, digits = 0), "%"),
          all_categorical() ~ c(0, 1)
        ),
        missing = "no"
      ) %>%
      gtsummary::add_n() %>%
      gtsummary::bold_labels() %>%
      # re write the characteristic column header to the custom label string
      gtsummary::modify_header(label ~ paste0("**", label_characteristic, "**")) %>%
      # remove the automated gtsummary continuous footnote
      gtsummary::modify_footnote(gtsummary::all_stat_cols() ~ NA) %>%
      # convert to native flextable for rock-solid Word document processing
      gtsummary::as_flex_table() %>%
      # remove the remaining footnote row block from the layout footer
      flextable::delete_part(part = "footer")
  }
  
  # logic to handle stratification
  if (!is.null(strata)) {
    data %>%
      # ensure the strata column exists before passing to tbl_strata
      gtsummary::tbl_strata(
        strata = all_of(strata),
        .tbl_fun = ~ build_summary(.x)
      )
  } else {
    build_summary(data)
  }
}

