# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' categorize numeric cols
#'
#' @param x a vector of numeric column
#' @param breaks numeric vector of breaks
#' @param labels character vector of labels
#'
#' @returns vector
#' @export
#'
#' @examples
#' cut_numeric(c(1:10), c(-Inf,5, Inf), c("<=5", ">=6"))
cut_numeric <- function(
    x, 
    breaks = c(16, 35, 60, Inf), 
    labels = c("16 - 35", "35 - 59", ">= 60")
){
  out <- cut(
    x,
    # 16 is the start, 35 and 60 are the breaks, inf covers everything above
    breaks = breaks,
    # labels for the resulting factor
    labels = labels,
    # include the lowest value and make intervals right-open [x, y)
    include.lowest = TRUE,
    right = FALSE
  )
  return(out)
}
