# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' categorize numeric cols
#'
#' @param x a vector of numeric column
#' @param breaks numeric vector of breaks
#' @param labels character vector of labels
#'
#' @returns vector
#' @export
#'
#' @examples
#' cut_numeric(c(1:10), c(-Inf,5, Inf), c("<=5", ">=6"))
cut_numeric <- function(
    x, 
    breaks = c(-Inf, 18, Inf), 
    labels = c("<18", ">=18")
){
  # find the true minimum value of the input vector
  min_val <- min(x, na.rm = TRUE)
  
  # if the minimum value is less than the first break point adjust the breaks and labels
  if (min_val < breaks[1]) {
    breaks <- c(min_val, breaks)
    labels <- c(paste(min_val, "-", breaks[2] - 1), labels)
  }
  
  out <- cut(
    x,
    # breaks now safely includes the true minimum value
    breaks = breaks,
    # updated labels matching the intervals
    labels = labels,
    # include the lowest value and make intervals right open
    include.lowest = TRUE,
    right = FALSE
  )
  return(out)
}
