# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Draw a Systematic Sample of Households Spreading Across Villages
#'
#' This function selects a systematic random sample of individual household rows 
#' from within counties. By sorting by village first, the systematic interval 
#' automatically spreads the selected sample evenly across the different villages.
#'
#' @param data A data frame containing raw household-level records.
#' @param county_var The bare or quoted column name identifying the county stratum.
#' @param village_id_var The bare or quoted column name identifying the unique village.
#' @param allocation_df A data frame containing two columns: the county identifier 
#'   and the allocated household sample size for that county.
#' @param alloc_size_var The bare or quoted column name in `allocation_df` 
#'   indicating the target sample size.
#' @param seed An integer value used to initialize the pseudo-random number generator. 
#'   Defaults to `42`.
#'
#' @return A data frame containing the systematically selected household rows.
#'
#' @importFrom dplyr group_by mutate ungroup inner_join arrange row_number filter across any_of n select
#' @importFrom rlang sym
#' @export
draw_systematic_across_villages <- function(
    data,
    county_var = "county",
    village_id_var = "village",
    allocation_df,
    alloc_size_var = "sample",
    seed = as.numeric(Sys.Date())
){

  set.seed(seed)

  joined_frame <- data %>%
    dplyr::inner_join(
      allocation_df,
      by = county_var
    ) %>%
    dplyr::arrange(
      dplyr::across(
        dplyr::any_of(
          c(county_var, village_id_var)
        )
      )
    )

  joined_frame %>%
    dplyr::group_by(
      dplyr::across(
        dplyr::any_of(county_var)
      )
    ) %>%
    dplyr::group_modify(~{

      df <- .x

      N <- nrow(df)
      n_target <- min(
        first(df[[alloc_size_var]]),
        N
      )

      k <- N / n_target

      start <- sample(
        seq_len(ceiling(k)),
        1
      )

      idx <- floor(
        start + (0:(n_target-1))*k
      )

      idx <- pmin(idx, N)

      df[idx, , drop = FALSE]

    }) %>%
    dplyr::ungroup()
}
