# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Draw PPS Household Sample
#'
#' @param data Household-level data frame.
#' @param county_var County variable name.
#' @param village_id_var Village identifier variable name.
#' @param allocation_df County allocation table.
#' @param alloc_size_var County sample size variable.
#' @param seed Random seed.
#'
#' @return Sampled household data frame.
#' @export
draw_pps_sample <- function(
    data,
    county_var = "county",
    village_id_var = "village",
    allocation_df,
    alloc_size_var = "sample",
    seed = as.numeric(Sys.Date())
){
  
  set.seed(seed)
  
  # safety check to handle cases where village grouping is missing or undefined
  # 
  has_village <- (!is.null(village_id_var)) && (village_id_var %in% names(data))
  
  if (!has_village) {
    internal_village_var <- "tmp_village_id"
    data <- data %>% 
      dplyr::mutate(!!internal_village_var := "single_cluster_fallback")
  } else {
    internal_village_var <- village_id_var
  }
  
  # ----------------------------
  # STEP 1: PPS village allocation
  # ----------------------------
  
  village_alloc <- data %>%
    dplyr::count(
      dplyr::across(
        dplyr::all_of(
          c(county_var, internal_village_var)
        )
      ),
      name = "village_size"
    ) %>%
    dplyr::left_join(
      allocation_df,
      by = county_var
    ) %>%
    dplyr::group_by(
      dplyr::across(
        dplyr::all_of(county_var)
      )
    ) %>%
    dplyr::mutate(
      
      county_total = sum(village_size),
      
      # isolate allocation variables and explicitly handle unmatched county labels
      # 
      target_size = dplyr::coalesce(as.numeric(.data[[alloc_size_var]]), 0),
      
      raw_alloc = (target_size * village_size) / county_total,
      
      base_alloc = floor(raw_alloc),
      
      frac = raw_alloc - base_alloc,
      
      remaining = dplyr::first(target_size) - sum(base_alloc),
      
      # safely assign remainders while shielding against zero target metrics
      # 
      sample_alloc = base_alloc + as.integer(
        dplyr::row_number(dplyr::desc(frac)) <= remaining & remaining > 0
      ),
      
      sample_alloc = dplyr::coalesce(sample_alloc, 0L)
      
    ) %>%
    dplyr::ungroup()
  
  # ----------------------------
  # STEP 2: Sample village-by-village
  # ----------------------------
  
  sampled <- village_alloc %>%
    
    dplyr::group_split(
      dplyr::across(
        dplyr::all_of(
          c(county_var, internal_village_var)
        )
      )
    ) %>%
    
    purrr::map_dfr(function(v){
      
      n_take <- v$sample_alloc[[1]]
      
      # enforce integer evaluation fallback to shield slice_sample from na values
      # 
      if (is.na(n_take) || n_take <= 0) {
        return(dplyr::slice(data, 0))
      }
      
      hh <- data %>%
        dplyr::semi_join(
          v,
          by = c(
            county_var,
            internal_village_var
          )
        )
      
      dplyr::slice_sample(
        hh,
        n = min(
          as.integer(n_take),
          nrow(hh)
        )
      )
      
    })
  
  # scrub internal placeholder column from memory profile if it was created
  # 
  if (!has_village) {
    sampled <- sampled %>% 
      dplyr::select(-dplyr::all_of(internal_village_var))
  }
  
  sampled
}
