# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Draw a Two-Stage Cluster Sample of Households
#'
#' This function performs two-stage cluster sampling within counties. In the 
#' first stage, a specified number of unique villages are selected randomly. In the 
#' second stage, a fixed number of households are randomly drawn from each 
#' of those selected villages. Both target sizes are pulled from the allocation frame.
#'
#' @param data A data frame containing raw household-level records.
#' @param county_var The bare or quoted column name identifying the county stratum.
#' @param village_id_var The bare or quoted column name identifying the unique village.
#' @param allocation_df A data frame containing columns for the county identifier, 
#'   the target village sample size, and the target household sample size per village.
#' @param alloc_villages_var The bare or quoted column name in `allocation_df` 
#'   indicating the number of villages to sample per county.
#' @param alloc_hh_var The bare or quoted column name in `allocation_df` 
#'   indicating the number of households to sample per chosen village.
#' @param seed An integer value used to initialize the pseudo-random number generator 
#'   for reproducible sampling. Defaults to `42`.
#'
#' @return A data frame containing the cluster-sampled household rows.
#'
#' @importFrom dplyr group_by mutate ungroup arrange row_number filter across any_of distinct n inner_join select
#' @importFrom rlang sym
#' @export
#'
#' @examples
#' \dontrun{
#' # dummy raw household data
#' raw_households <- data.frame(
#'   county_id = rep(c("County_A", "County_B"), each = 15),
#'   village_id = c(rep("V1", 5), rep("V2", 5), rep("V3", 5), 
#'                  rep("V4", 5), rep("V5", 5), rep("V6", 5)),
#'   household_id = paste0("HH_", 1:30)
#' )
#'
#' # multi-stage target allocations dataframe
#' cluster_allocations <- data.frame(
#'   county_id = c("County_A", "County_B"),
#'   target_villages = c(2, 2),
#'   target_hh_per_village = c(3, 2)
#' )
#'
#' # run dynamic cluster sampling
#' cluster_sample <- draw_cluster_sample(
#'   data = raw_households,
#'   county_var = "county_id",
#'   village_id_var = "village_id",
#'   allocation_df = cluster_allocations,
#'   alloc_villages_var = "target_villages",
#'   alloc_hh_var = "target_hh_per_village",
#'   seed = 42
#' )
#' }
draw_cluster_sample <- function(
    data,
    county_var = "county",
    village_id_var = "village",
    allocation_df,
    alloc_villages_var = "target_villages",
    alloc_hh_var = "target_hh_per_village",
    seed = 42
){

  set.seed(seed)

  selected_villages <- data %>%
    dplyr::distinct(
      dplyr::across(
        dplyr::any_of(
          c(county_var, village_id_var)
        )
      )
    ) %>%
    dplyr::inner_join(
      allocation_df,
      by = county_var
    ) %>%
    dplyr::group_by(
      dplyr::across(
        dplyr::any_of(county_var)
      )
    ) %>%
    dplyr::slice_sample(
      n = min(
        dplyr::n(),
        first(.data[[alloc_villages_var]])
      )
    ) %>%
    dplyr::ungroup()

  data %>%
    dplyr::inner_join(
      selected_villages,
      by = c(county_var, village_id_var)
    ) %>%
    dplyr::group_by(
      dplyr::across(
        dplyr::any_of(
          c(county_var, village_id_var)
        )
      )
    ) %>%
    dplyr::slice_sample(
      n = min(
        dplyr::n(),
        first(.data[[alloc_hh_var]])
      )
    ) %>%
    dplyr::ungroup()
}
