# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Draw PPS Household Sample
#'
#' @param data Household-level data frame.
#' @param county_var County variable name.
#' @param village_id_var Village identifier variable name.
#' @param allocation_df County allocation table.
#' @param alloc_size_var County sample size variable.
#' @param seed Random seed.
#'
#' @return Sampled household data frame.
#' @export
draw_pps_sample <- function(
    data,
    county_var = "county",
    village_id_var = "village",
    allocation_df,
    alloc_size_var = "sample",
    seed = as.numeric(Sys.Date())
){
  
  set.seed(seed)
  
  # ----------------------------
  # STEP 1: PPS village allocation
  # ----------------------------
  
  village_alloc <- data %>%
    dplyr::count(
      dplyr::across(
        dplyr::all_of(
          c(county_var, village_id_var)
        )
      ),
      name = "village_size"
    ) %>%
    dplyr::left_join(
      allocation_df,
      by = county_var
    ) %>%
    dplyr::group_by(
      dplyr::across(
        dplyr::all_of(county_var)
      )
    ) %>%
    dplyr::mutate(
      
      county_total = sum(village_size),
      
      raw_alloc =
        (.data[[alloc_size_var]] *
           village_size) /
        county_total,
      
      base_alloc = floor(raw_alloc),
      
      frac = raw_alloc - base_alloc,
      
      remaining =
        first(.data[[alloc_size_var]]) -
        sum(base_alloc),
      
      sample_alloc =
        base_alloc +
        as.integer(
          dplyr::row_number(
            dplyr::desc(frac)
          ) <= remaining
        )
      
    ) %>%
    dplyr::ungroup()
  
  # ----------------------------
  # STEP 2: Sample village-by-village
  # ----------------------------
  
  sampled <- village_alloc %>%
    
    dplyr::group_split(
      dplyr::across(
        dplyr::all_of(
          c(county_var, village_id_var)
        )
      )
    ) %>%
    
    purrr::map_dfr(function(v){
      
      n_take <- v$sample_alloc[[1]]
      
      hh <- data %>%
        dplyr::semi_join(
          v,
          by = c(
            county_var,
            village_id_var
          )
        )
      
      dplyr::slice_sample(
        hh,
        n = min(
          n_take,
          nrow(hh)
        )
      )
      
    })
  
  sampled
}

