# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Draw a Sample of Households Proportional to Village Size
#'
#' This function selects a stratified random sample of individual household rows 
#' from within counties. The probability of a household being selected is 
#' proportional to the total size (household count) of the village it belongs to.
#'
#' @param data A data frame containing raw household-level records.
#' @param county_var The bare or quoted column name identifying the county stratum.
#' @param village_id_var The bare or quoted column name identifying the unique village.
#' @param allocation_df A data frame containing two columns: the county identifier 
#'   and the allocated household sample size for that county.
#' @param alloc_size_var The bare or quoted column name in `allocation_df` 
#'   indicating the target sample size.
#' @param seed An integer value used to initialize the pseudo-random number generator 
#'   for reproducible sampling. Defaults to `42`.
#'
#' @return A data frame containing the individually selected household rows.
#'
#' @importFrom dplyr group_by mutate ungroup inner_join arrange row_number filter across any_of desc n
#' @importFrom rlang sym
#' @export
#'
#' @examples
#' \dontrun{
#' # dummy raw household data
#' raw_households <- data.frame(
#'   county_id = rep(c("County_A", "County_B"), each = 10),
#'   village_id = c(rep("V1", 3), rep("V2", 7), rep("V3", 4), rep("V4", 6)),
#'   household_id = paste0("HH_", 1:20)
#' )
#'
#' # household sample size targets per county
#' target_allocations <- data.frame(
#'   county_id = c("County_A", "County_B"),
#'   sample_size = c(2, 3)
#' )
#'
#' # run reproducible pps household sampling
#' pps_household_sample <- draw_pps_sample(
#'   data = raw_households,
#'   county_var = "county_id",
#'   village_id_var = "village_id",
#'   allocation_df = target_allocations,
#'   alloc_size_var = "sample_size",
#'   seed = 123
#' )
#' }
draw_pps_sample <- function(
    data, 
    county_var = "county", 
    village_id_var = "village", 
    allocation_df,
    alloc_size_var = "sample",
    seed = as.numeric(Sys.Date())
) {
  
  # preserve global environment random seed state if it exists
  if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
    old_seed <- get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
    on.exit(assign(".Random.seed", old_seed, envir = .GlobalEnv))
  }
  
  # set the pseudo-random seed state for this execution context
  set.seed(seed)
  
  # calculate village size and append it back to every household row natively
  household_weights <- data %>%
    dplyr::group_by(dplyr::across(dplyr::any_of(c(county_var, village_id_var)))) %>%
    dplyr::mutate(village_size = dplyr::n()) %>%
    dplyr::ungroup()
  
  # join the target household allocations per county
  joined_frame <- dplyr::inner_join(
    household_weights, 
    allocation_df, 
    by = rlang::set_names(county_var, county_var)
  )
  
  # generate a uniform random component combined with size weights for pps without replacement
  # then slice the top target records per county grouping
  sampled_households <- joined_frame %>%
    dplyr::group_by(dplyr::across(dplyr::any_of(county_var))) %>%
    dplyr::mutate(
      rand_weight = stats::runif(dplyr::n())^(1 / .data$village_size)
    ) %>%
    dplyr::arrange(dplyr::desc(.data$rand_weight), .by_groups = TRUE) %>%
    dplyr::filter(dplyr::row_number() <= unique(!!rlang::sym(alloc_size_var))) %>%
    dplyr::ungroup() %>%
    dplyr::select(-.data$rand_weight)
  
  return(sampled_households)
}
