# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Export/write gtsummary output to excel workbook
#'
#' @param list_of_objects list of `gtsummary` object
#' @param file_name character. output filename and associated path
#'
#' @returns NULL
#' @export
#'
#' @examples
#' \dontrun{export_to_excel_formatted()} 
export_to_excel_formatted <- function(
    list_of_objects,
    file_name = paste0("UNOCHA_Summary_Report_", Sys.Date(), ".xlsx")
) {
  
  # create the workbook object
  wb <- openxlsx::createWorkbook()
  
  # define styles
  neg_style <- createStyle(fontColour = "#FF0000", textDecoration = "bold")
  # style for bolding the row headers (the first column)
  bold_header_style <- createStyle(textDecoration = "bold")
  
  # iterate through the named list
  purrr::iwalk(list_of_objects, function(obj, sheet_name) {
    
    openxlsx::addWorksheet(wb, sheet_name)
    
    # conversion logic
    df_to_write <- if (inherits(obj, "gtsummary")) {
      as_tibble(obj)
    } else {
      as.data.frame(obj)
    }
    
    openxlsx::writeData(wb, sheet_name, df_to_write)
    
    # 1. bold the row headers (first column)
    # rows starts at 2 to skip the excel header row
    openxlsx::addStyle(
      wb, 
      sheet_name, 
      style = bold_header_style, 
      cols = 1, 
      rows = 2:(nrow(df_to_write) + 1), 
      gridExpand = TRUE
    )
    
    # 2. apply red color coding for negative values
    openxlsx::conditionalFormatting(
      wb, 
      sheet_name, 
      cols = 1:ncol(df_to_write), 
      rows = 2:(nrow(df_to_write) + 1), 
      rule = "< 0", 
      style = neg_style
    )
    
    openxlsx::setColWidths(wb, sheet_name, cols = 1:ncol(df_to_write), widths = "auto")
  })
  
  openxlsx::saveWorkbook(wb, file = file.path("output", file_name), overwrite = TRUE)
}
