# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Export a sheet to existing workbook
#'
#' @param list_of_objects list of `gtsummary` object
#' @param sheetname character. worksheet name
#' @param file_name character. output file name
#' @param output_dir character. output directory
#'
#' @returns NULL
#' @export
#'
#' @examples
#' \dontrun{export_to_excel_appended()}
export_to_excel_appended <- function(
    list_of_objects = df_target_p,
    sheetname = "Target and Registered ESR",
    file_name = paste0("UNOCHA_Summary_Report_", Sys.Date(), ".xlsx"),
    output_dir = "output"
) {
  
  # create output dir
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # build full path safely
  file_path <- file.path(output_dir, basename(file_name))
  
  message("Using file path: ", normalizePath(file_path, mustWork = FALSE))
  
  # load existing workbook OR create new
  if (file.exists(file_path)) {
    
    message("Loading existing workbook...")
    
    wb <- tryCatch(
      openxlsx::loadWorkbook(file_path),
      error = function(e) {
        message("Failed to load workbook: ", e$message)
        openxlsx::createWorkbook()
      }
    )
    
  } else {
    
    message("Workbook does not exist. Creating new workbook...")
    wb <- openxlsx::createWorkbook()
    
  }
  
  # excel sheet name limit
  sheetname <- substr(sheetname, 1, 31)
  
  # remove existing sheet if present
  if (sheetname %in% names(wb)) {
    openxlsx::removeWorksheet(wb, sheetname)
  }
  
  addWorksheet(wb, sheetname)
  
  # styles
  header_style <- createStyle(
    fontSize = 12,
    textDecoration = "bold",
    fontColour = "#0066A1"
  )
  
  bold_row_style <- openxlsx::createStyle(textDecoration = "bold")
  
  neg_style <- openxlsx::createStyle(
    fontColour = "#FF0000",
    textDecoration = "bold"
  )
  
  current_row <- 1
  
  purrr::iwalk(list_of_objects, function(obj, list_name) {
    
    df_to_write <- if (inherits(obj, "gtsummary")) {
      as_tibble(obj)
    } else {
      as.data.frame(obj)
    }
    
    # section title
    openxlsx::writeData(
      wb,
      sheet = sheetname,
      x = list_name,
      startRow = current_row
    )
    
    openxlsx::addStyle(
      wb,
      sheet = sheetname,
      style = header_style,
      cols = 1,
      rows = current_row
    )
    
    current_row <<- current_row + 1
    
    # write table
    openxlsx::writeData(
      wb,
      sheet = sheetname,
      x = df_to_write,
      startRow = current_row,
      headerStyle = bold_row_style
    )
    
    # bold first column
    if (nrow(df_to_write) > 0) {
      
      openxlsx::addStyle(
        wb,
        sheet = sheetname,
        style = bold_row_style,
        cols = 1,
        rows = (current_row + 1):(current_row + nrow(df_to_write)),
        gridExpand = TRUE,
        stack = TRUE
      )
      
      openxlsx::conditionalFormatting(
        wb,
        sheet = sheetname,
        cols = 1:ncol(df_to_write),
        rows = (current_row + 1):(current_row + nrow(df_to_write)),
        rule = "<0",
        style = neg_style
      )
    }
    
    current_row <<- current_row + nrow(df_to_write) + 3
  })
  
  # autofit
  openxlsx::setColWidths(
    wb,
    sheet = sheetname,
    cols = 1:50,
    widths = "auto"
  )
  
  # save
  openxlsx::saveWorkbook(
    wb,
    file = file_path,
    overwrite = TRUE
  )
  
  message("Workbook saved successfully.")
}
