# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Export a list of dataframes to word
#'
#' @param table_list list of dataframes
#' @param doc_path character vector of output directory
#' @importFrom flextable  body_add_flextable
#' @importFrom officer body_add_par body_add_break 
#'
#' @returns NULL
#' @export
#'
#' @examples
#' \dontrun{export_list_to_word()}
export_list_to_word <- function(table_list, doc_path) {
  
  # initialize a new word document
  doc <- officer::read_docx()
  
  # iterate through the named list
  # .x is the table/df, .y is the name of the list element
  purrr::iwalk(table_list, function(.x, .y) {
    
    # logic to handle different table types
    if (inherits(.x, "gtsummary")) {
      # convert gtsummary to flextable
      ft <- gtsummary::as_flex_table(.x)
    } else {
      # treat as standard dataframe and format
      ft <- flextable::flextable(.x) %>%
        flextable::theme_booktabs() %>%
        flextable::autofit() %>%
        flextable::bold(part = "header")
    }
    
    # add the header and the table to the document
    doc <<- doc %>%
      # use the list name as a header 2
      body_add_par(.y, style = "heading 2") %>%
      body_add_flextable(ft) %>%
      # add a small spacer after each table
      body_add_par("") 
  })
  
  # save the completed document
  print(doc, target = doc_path)
}
