# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' find unique extra records in a matched dataset missing from the reference payroll
#'
#' @param matched_df dataframe containing the processed matched records (e.g., df_matched)
#' @param payroll_df dataframe containing the raw reference payroll records (e.g., d_pay_out)
#' @param target_agency character string identifying the specific agency group to audit
#' @param matched_agency_col character name of the agency column in matched_df
#' @param payroll_agency_col character name of the agency column in payroll_df
#'
#' @returns a filtered dataframe containing the rogue records present only in matched_df
#' @export
find_extra_agency_records <- function(matched_df = df_matched, 
                                      payroll_df = d_pay_out, 
                                      target_agency = "ALDEF", 
                                      matched_agency_col = "enum_egency", 
                                      payroll_agency_col = "partner") {
  
  # slice down both data matrices to focus exclusively on the target agency group
  subset_matched <- matched_df %>%
    dplyr::filter(.data[[matched_agency_col]] == target_agency)
  
  subset_payroll <- payroll_df %>%
    dplyr::filter(.data[[payroll_agency_col]] == target_agency)
  
  # capture tracking records that exist in the match pool but have no match on payroll
  extra_records <- subset_matched %>%
    dplyr::anti_join(
      subset_payroll,
      by = c(
        "id_number" = "id_number",
        "telephone_number" = "telephone_number"
      )
    )
  
  return(extra_records)
}
