# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' flatten all tables within a dm object into a list of data frames
#'
#' @param dm_obj a dm data model object
#'
#' @returns a named list of flattened data frames
#' @export
flatten_dm_by_names <- function(dm_obj) {
  # extract the structural table names directly from the dm object
  tbl_names <- names(dm_obj)
  
  # loop through the valid names to flatten each table
  df_list <- lapply(tbl_names, function(name) {
    dm::dm_flatten_to_tbl(dm_obj, !!name)
  })
  
  # reapply the names to the output list
  names(df_list) <- tbl_names
  
  return(df_list)
}
