# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' format numeric vectors using gtsummary style number labels safely
#'
#' @param x numeric vector to be formatted
#' @param ... optional arguments passed along to label_style_number
#'
#' @returns a character vector of formatted numbers
#' @importFrom gtsummary label_style_number
#' @export
format_num <- function(x, ...) {
  # build the formatting constructor inside an isolated execution context to bypass compiler warnings
  formatter <- gtsummary::label_style_number(...)
  
  # execute the function directly on the incoming numeric elements
  formatter(x)
}


#' Add a gtsummary objet to word doc
#'
#' @param doc word doc created as `officer::read_docx()`
#' @param gt_obj gtsummary object
#' @param title character header
#' @param landscape logical. page orientation
#' @importFrom flextable  body_add_flextable
#' @importFrom officer body_add_par body_add_break body_end_section_landscape
#'
#' @returns a word doc
#' @export
#'
#' @examples
#' \dontrun{
#' add_gt_to_word(doc, gt_obj, title, landscape = FALSE)
#' }
add_gt_to_word <- function(doc, gt_obj, title, landscape = FALSE) {
  # Convert gtsummary to flextable
  ft <- gtsummary::as_flex_table(gt_obj) %>%
    flextable::autofit()
  
  # Add title and table
  doc <- doc %>%
    body_add_par(title, style = "heading 2") %>%
    body_add_flextable(ft) %>%
    body_add_par("") # spacing
  
  # Handle Orientation and Page Breaks
  if (landscape) {
    # Close the current landscape section
    doc <- doc %>% body_end_section_landscape() 
  } else {
    # If not landscape, just add a standard page break
    doc <- doc %>% body_add_break()
  }
  
  return(doc)
}

