# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create the target beneficiary verification criteria and indicators summary
#'
#' @description
#' Builds a two column matrix pairing each humanitarian vulnerability 
#' criterion alongside its designated operational indicator visually 
#' merging repeating criteria rows and introducing complete outer frame grids 
#' that fully enclose column headers with explicit bold top and bottom lines
#'
#' @param df dataframe of verification criteria
#' @param title character vector of title
#' @return A styled gt table object containing the merged two column layout with 
#' fully enclosed bold grid line formatting
#'
#' @importFrom tibble tibble
#' @importFrom dplyr mutate lag
#' @importFrom gt gt cols_label tab_header tab_source_note pct tab_options px cells_body tab_style cell_borders cells_column_labels cell_fill
#'
#' @export
gen_verification_criteria_table <- function(
    df = verification_criteria,
    title = "Vulnerability Criteria"
    ) {
  
  # instantiate the explicit two column data frame mapping

  
  # track total row count
  total_rows <- nrow(df)
  
  # track the indices where a new criteria block begins for main horizontal lines
  main_grid_rows <- c(7, 12, 15, 16)
  
  # process data internally to blank out sequential duplicate row labels for visual merge
  display_df <- df %>%
    dplyr::mutate(
      Criteria = ifelse(Criteria == dplyr::lag(Criteria, default = ""), "", Criteria)
    )
  
  # initialize gt table visualization structure
  styled_table <- display_df %>%
    gt::gt() %>%
  { if (!is.null(title) && nzchar(as.character(title))) 
      gt::tab_header(., title = title) 
    else . } %>%
    gt::cols_label(
      Criteria = "Criteria",
      Indicator = "Indicator"
    ) %>%
    gt::tab_source_note(
      source_note = "Acronym Definitions: OTP - Outpatient Therapeutic Program; SFP - Supplementary Feeding Program; FCS - Food Consumption Score; HHs - Households"
    ) %>%
    
    # apply a standard baseline horizontal grid line separating every single indicator row
    gt::tab_style(
      style = gt::cell_borders(
        sides = "top",
        color = "#d3d3d3",
        weight = gt::px(1),
        style = "solid"
      ),
      locations = gt::cells_body(rows = 1:total_rows)
    ) %>%
    
    # apply acted deep blue background fill with white text for column labels
    gt::tab_style(
      style = list(
        gt::cell_fill(color = "#0B1054"),
        gt::cell_text(color = "white", weight = "bold")
      ),
      locations = gt::cells_column_labels(columns = c("Criteria", "Indicator"))
    ) %>%
    
    # overlay bold main horizontal block dividers within the body row structures
    gt::tab_style(
      style = gt::cell_borders(
        sides = "top",
        color = "#0B1054",
        weight = gt::px(2.25),
        style = "solid"
      ),
      locations = gt::cells_body(rows = main_grid_rows)
    ) %>%
    
    # force line above the column header to be bold in the interactive viewer
    gt::tab_style(
      style = gt::cell_borders(
        sides = "top",
        color = "#0B1054",
        weight = gt::px(2.5),
        style = "solid"
      ),
      locations = gt::cells_column_labels(columns = c("Criteria", "Indicator"))
    ) %>%
    
    # force line below the column header to be bold in the interactive viewer
    gt::tab_style(
      style = gt::cell_borders(
        sides = "bottom",
        color = "#0B1054",
        weight = gt::px(2.5),
        style = "solid"
      ),
      locations = gt::cells_column_labels(columns = c("Criteria", "Indicator"))
    ) %>%
    
    # construct an explicit thick bottom line at the absolute base of the table body rows
    gt::tab_style(
      style = gt::cell_borders(
        sides = "bottom",
        color = "#0B1054",
        weight = gt::px(2.5),
        style = "solid"
      ),
      locations = gt::cells_body(rows = total_rows)
    ) %>%
    
    # establish a heavy vertical dividing line between the criteria and indicator columns
    gt::tab_style(
      style = gt::cell_borders(
        sides = "right",
        color = "#0B1054",
        weight = gt::px(2),
        style = "solid"
      ),
      locations = list(
        gt::cells_body(columns = "Criteria"),
        gt::cells_column_labels(columns = "Criteria")
      )
    ) %>%
    
    # construct complete left outer frame border enclosing headers and cell body rows
    gt::tab_style(
      style = gt::cell_borders(
        sides = "left",
        color = "#0B1054",
        weight = gt::px(2.5),
        style = "solid"
      ),
      locations = list(
        gt::cells_body(columns = "Criteria"),
        gt::cells_column_labels(columns = "Criteria")
      )
    ) %>%
    
    # construct complete right outer frame border enclosing headers and cell body rows
    gt::tab_style(
      style = gt::cell_borders(
        sides = "right",
        color = "#0B1054",
        weight = gt::px(2.5),
        style = "solid"
      ),
      locations = list(
        gt::cells_body(columns = "Indicator"),
        gt::cells_column_labels(columns = "Indicator")
      )
    ) %>%
    
    # control options directly to stop default rendering layers from resetting manual borders
    gt::tab_options(
      table.font.size = gt::pct(95),
      heading.align = "left",
      table.width = gt::pct(100),
      table.border.top.style = "none",
      table.border.bottom.style = "none",
      heading.border.bottom.style = "none",
      column_labels.border.top.style = "none",
      column_labels.border.bottom.style = "none"
    )
  
  return(styled_table)
}
