# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create the target beneficiary verification criteria and indicators summary
#'
#' @description
#' Builds a two column matrix pairing each humanitarian vulnerability 
#' criterion alongside its designated operational indicator visually 
#' merging repeating criteria rows and introducing complete outer frame grids 
#' that fully enclose column headers with explicit bold top and bottom lines
#'
#' @param df dataframe of verification criteria
#' @param title character vector of title
#' @return A styled flextable object containing the merged two column layout with 
#' fully enclosed bold grid line formatting
#'
#' @importFrom tibble tibble
#' @importFrom dplyr mutate lag
#' @importFrom flextable flextable as_paragraph as_chunk align valign width border_outer border_inner_h border_inner_v bg color bold font set_caption delete_part add_footer_lines
#' @importFrom officer fp_border fp_text
#'
#' @export
gen_verification_criteria_table <- function(
    df = verification_criteria,
    title = "Vulnerability Criteria"
    ) {
  
  # track total row count
  total_rows <- nrow(df)
  
  # track the indices where a new criteria block begins for main horizontal lines
  main_grid_rows <- c(7, 12, 15, 16)
  
  # define the explicit border properties using officer
  heavy_border <- officer::fp_border(color = "#0B1054", width = 2.5, style = "solid")
  mid_border   <- officer::fp_border(color = "#0B1054", width = 2, style = "solid")
  thin_border  <- officer::fp_border(color = "#d3d3d3", width = 1, style = "solid")
  
  # build the flextable layout structure
  styled_table <- flextable::flextable(df) %>%
    # visually merge repeating cell items sequentially along the vertical axis
    flextable::merge_v(j = ~ Criteria) %>%
    # map alignments and set relative layout sizing to fit standard pages
    flextable::align(align = "left", part = "all") %>%
    flextable::valign(valign = "top", part = "body") %>%
    flextable::width(j = "Criteria", width = 2.2) %>%
    flextable::width(j = "Indicator", width = 4.3) %>%
    
    # apply deep blue background fill with white bold text for column labels
    flextable::bg(bg = "#0B1054", part = "header") %>%
    flextable::color(color = "white", part = "header") %>%
    flextable::bold(part = "header") %>%
    
    # apply a standard baseline horizontal grid line separating every single indicator row
    flextable::border_inner_h(border = thin_border, part = "body") %>%
    
    # overlay bold main horizontal block dividers within the body row structures
    flextable::hline(i = (main_grid_rows - 1), border = mid_border, part = "body") %>%
    
    # construct complete outer frame borders and center divider line enclosing headers and rows
    flextable::border_outer(border = heavy_border, part = "all") %>%
    flextable::border_inner_v(border = mid_border, part = "all") %>%
    
    # add font settings and map the source footnote notes cleanly to the bottom layout
    flextable::font(fontname = "Arial", part = "all") %>%
    flextable::add_footer_lines(
      values = "Acronym Definitions: OTP - Outpatient Therapeutic Program; SFP - Supplementary Feeding Program; FCS - Food Consumption Score; HHs - Households"
    ) %>%
    flextable::font(fontname = "Arial", part = "footer")
  
  return(styled_table)
}
