# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' filter and deduplicate beneficiary logs by agency partner
#'
#' @param df dataframe containing master registry logs
#' @param partner character keyword used to identify the target agency, defaults to 'pgi'
#' @param columns character vector of column names to distinct by, defaults to c('ben_name', 'ben_id_number')
#'
#' @returns a deduplicated dataframe containing partner specific records
#' @importFrom dplyr filter distinct across all_of
#' @export
get_partner_beneficiaries <- function(df = df_out, partner = "pgi", columns = c("ben_name", "ben_id_number")) {
  
  # match agency keyword and remove duplicates based on dynamic columns argument configuration
  processed_df <- df %>%
    dplyr::filter(grepl(partner, enum_egency, ignore.case = TRUE)) %>%
    dplyr::distinct(dplyr::across(dplyr::all_of(columns)), .keep_all = TRUE)
  
  return(processed_df)
}
