# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' get duplicate beneficiaries on select variables
#'
#' @param x dataframe
#' @param vars_to_check character vector of variables to check
#' @param phone_var character vector. phone number variable for hard check
#' @param name_var character vector. name of respondent
#' @importFrom dplyr group_by across n n_distinct filter any_of ungroup distinct
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{get_duplicates()}
get_duplicates <- function(
    x,
    vars_to_check = c("benef_name", "ben_number"),
    phone_var = "ben_number",
    name_var = "benef_name"
){
  
  # 1. find phone sharing: same phone, different names
  phone_sharing <- x %>%
    group_by(across(any_of(phone_var))) %>%
    filter(n() > 1 & n_distinct(across(any_of(name_var))) > 1)
  
  # 2. find name sharing: same name, different phones
  name_sharing <- x %>%
    group_by(across(any_of(name_var))) %>%
    filter(n() > 1 & n_distinct(across(any_of(phone_var))) > 1)
  
  # 3. find exact duplicates across the vars_to_check
  exact_dups <- x %>%
    group_by(across(any_of(vars_to_check))) %>%
    filter(n() > 1)
  
  # combine all instances and remove overlapping rows
  res <- bind_rows(phone_sharing, name_sharing, exact_dups) %>%
    distinct() %>%
    ungroup()
  
  # sort by the primary variables for easy review
  res %>%
    arrange(across(any_of(vars_to_check)))
}
