# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' get duplicate rows, track the checked field, and subset down to designated columns via an argument
#'
#' @param data a dataframe or tibble
#' @param col the unquoted column name to check for duplicates, defaults to ben_name
#' @param cols_select a list of unquoted column expressions to select, defaults to a predefined set
#'
#' @returns a filtered and pruned dataframe of duplicate rows
#' @importFrom rlang ensyms exprs
#' @importFrom janitor get_dupes
#' @importFrom dplyr mutate select
#' @export
get_dupes_with_name <- function(
    data, 
    col = ben_name, 
    cols_select = rlang::exprs(county, enum_egency, enum_name,ben_name, ben_id_number,reg_num, dup_col, uuid)
) {
  
  # capture the checking columns safely as a list of symbols
  col_syms <- rlang::ensyms(col)
  
  # convert the captured symbols into character strings for label grouping
  col_strings <- as.character(col_syms)
  combined_label <- paste(col_strings, collapse = ", ")
  
  # run the janitor deduplication filter across all target symbols and append the tracking string
  processed_df <- data %>%
    janitor::get_dupes(!!!col_syms) %>%
    dplyr::mutate(dup_col = combined_label)
  
  # inject and combine the checked column symbols directly into the selection expression list
  final_select_exprs <- unique(c(col_syms, cols_select))
  
  # evaluate the complete unified selection expression list dynamically
  result <- processed_df %>%
    dplyr::select(!!!final_select_exprs)
  
  return(result)
}
