# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get personally identifying columns
#'
#' @param df dataframe
#' @param vars string of identifying columns
#'
#' @returns a list of 3 dataframes: identifying, de-identified, and original df
#' @export
#'
#' @examples
#' \dontrun{get_pii()}
get_pii <- function(
    df = df_clean,
    vars = c("lat", "long", "name", "mobile", "gps", "phone", "enum_num$", "^(enum|reg|ben|proxy|sec)_.*(name|num|id)")
){
  cols <- paste(vars, collapse = "|")
  df_pii <- df %>% select(
    grep(cols, names(.))
  )
  df_depii <- df %>%
    dplyr::select(
      -grep(cols, names(.))
    )
  out <- list(df_pii, df_depii, df) %>%
    purrr::set_names(c("personaly-identifying", "de-identified", "original-data"))
  return(out)
}
