# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' get distinct beneficiaries on select variables
#'
#' @param x dataframe
#' @param vars_to_check character vector of columns to check
#' @param phone_var character vector of phone number column
#' @param name_var character vector of respondent name
#' @importFrom dplyr group_by across n n_distinct filter any_of ungroup distinct select pull row_number bind_rows 
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{get_distinct()}
get_distinct <- function(
    x,
    vars_to_check = c("benef_name", "ben_number"),
    phone_var = "ben_number",
    name_var = "benef_name"
){
  # identify the ids or row indices of all duplicates first
  # we use your duplicate logic to find what to exclude
  duplicates <- x %>%
    # use row_number to keep track of exactly which rows are flagged
    mutate(temp_id = row_number()) %>%
    {
      # find rows that fail any of the duplicate checks
      bind_rows(
        # scenario 1: shared phone, different names
        group_by(., across(any_of(phone_var))) %>% 
          filter(n() > 1 & n_distinct(across(any_of(name_var))) > 1),
        
        # scenario 2: shared name, different phones
        group_by(., across(any_of(name_var))) %>% 
          filter(n() > 1 & n_distinct(across(any_of(phone_var))) > 1),
        
        # scenario 3: exact duplicates
        group_by(., across(any_of(vars_to_check))) %>% 
          filter(n() > 1)
      )
    } %>%
    pull(temp_id) %>%
    unique()
  
  # return the original data minus the duplicate rows
  x %>%
    mutate(temp_id = row_number()) %>%
    filter(!(temp_id %in% duplicates)) %>%
    select(-temp_id)
}
