# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Split dataset by expenditure thresholds
#'
#' @param df A dataframe containing the target columns.
#' @param threshold The numeric ceiling limit for filtering. Default is 50000.
#'
#' @return A list containing two dataframes: "clean_data" and "extreme_data".
#' @export
get_outlier_income <- function(df, threshold = 50000) {
  
  # identify target columns matching the regex pattern
  # lower case comments without dots or dashes
  target_cols <- grep("amnt$|totalhhexp", names(df), value = TRUE)
  
  # return original data and an empty shell if no target columns are found
  # lower case comments without dots or dashes
  if (length(target_cols) == 0) {
    return(list(
      clean_data = df,
      extreme_data = df[0, , drop = FALSE]
    ))
  }
  
  # evaluate threshold condition across all matched columns ignoring NA values
  # lower case comments without dots or dashes
  has_extreme_value <- rowSums(
    sapply(df[target_cols], function(col) {
      if (is.numeric(col)) {
        return(!is.na(col) & col > threshold)
      } else {
        return(rep(FALSE, length(col)))
      }
    }), 
    na.rm = TRUE
  ) > 0
  
  # split data into clean records and extreme outliers
  # lower case comments without dots or dashes
  list(
    clean_data = df[!has_extreme_value, , drop = FALSE],
    extreme_data = df[has_extreme_value, , drop = FALSE]
  )
}
