# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Read partner registration edit files
#'
#' @param partner character string of partners e.g., "PGI" 
#' @param cols_exclude character vector of columns to exclude from edits
#' @param sheet_name character vector of workbook sheet name
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{get_edit_data()}
get_edit_data <- function(
    partner = "PGI",
    cols_exclude = c("village", "ben_name"),
    sheet_name = NULL
){
  p_file <- list.files(
    file.path(here::here(),"edits"), pattern = partner, full.names = TRUE,
    ignore.case = TRUE
  )
  if(!is.null(sheet_name)){
    sheet_f <- sheet_name
  }else{
    sheet_f <- readxl::excel_sheets(p_file)
  }
  
  df <- readxl::read_excel(p_file, sheet = sheet_f) %>%
    clean_names()   %>% mutate(
      ben_name = stringr::str_squish(ben_name) %>% stringr::str_to_title()
    ) 
  df_1 <- df %>%
    
    # left_join(
    #   df_out %>% 
    #   #   filter(
    #   #   grepl("Tana", county, ignore.case = T)
    #   # ) %>%
    #     select(
    #     ben_name, ben_id_number
    #   )
    # ) %>% 
    filter(
      !grepl(paste(cols_exclude, collapse = "|"), var_to_change)
    )
  return(df_1)
}
