# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' separate villages collapsed by forward slash ("|")
#'
#' @param data1 dataframe. ESR/partner data
#' @param data2 dataframe. registration data
#'
#' @returns a dataframe
#' @importFrom stringr str_extract str_replace_all
#' @export
#'
#' @examples
#' \dontrun{get_standard_villages(data1 = df_partner, data2 = df_clean)}
get_standard_villages <- function(data1 = df_partner, data2 = df_clean) {
  
  # get unique reference villages and sort by length descending
  # this ensures long names are matched before substrings
  villages <- unique(data2$village2)
  villages_sorted <- villages[order(nchar(villages), decreasing = TRUE)]
  
  # escape special characters and collapse for regex
  village_pattern <- paste(stringr::str_escape(villages_sorted), collapse = "|")
  
  data1 %>%
    # separate rows based on the forward slash
    # this turns "village1/village2" into two distinct rows
    tidyr::separate_rows(village, sep = "/") %>%
    dplyr::mutate(
      # extract the standard name using the pattern
      village2 = str_extract(village, regex(village_pattern, ignore_case = TRUE)),
      # capitalize first letters of village names as per your requirement
      # this handles slashes if they appear in the result
      village2 = str_replace_all(village2, "(^|/)([a-z])", function(m) toupper(m))
    )
}
