# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Extract column names from a data dictionary based on structural boundaries
#'
#' @param dict dataframe representing the data dictionary
#' @param name_col string. The column containing the variable names to extract
#' @param vulnerability_df a dataframe with vulnerability categories
#' @param vulnerability_class character vector of vulnerability class
#'
#' @returns a character vector of column names
#' @export
get_group_cols <- function(dict, vulnerability_df, vulnerability_class = "physio", name_col = "name") {
  
  df <- vulnerability_df %>%
    dplyr::filter(
      grepl(vulnerability_class, label, ignore.case = TRUE)
    )
  dict %>%
    dplyr::filter(n >= df$n & n < df$n_end) %>%
    # remove true NAs and any literal "NA" character strings
    dplyr::filter(!is.na(!!rlang::sym(name_col)) & !!rlang::sym(name_col) != "NA") %>%
    dplyr::pull(!!rlang::sym(name_col))
}
