# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' find partial matches between focal and beneficiary
#'
#' @param df dataframe
#' @param focal character vector of focal variable
#' @param beneficiary character vector of beneficiary variable
#'
#' @returns a dataframe
#' @export
#'
#' @examples
#' \dontrun{get_partial_matches()}
get_partial_matches <- function(df, focal = "focal_name", beneficiary = "benef_name") {
  df %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      is_partial = stringr::str_detect(.data[[focal]], fixed(.data[[beneficiary]])) | 
        stringr::str_detect(.data[[beneficiary]], fixed(.data[[focal]]))
    ) %>% 
    dplyr::ungroup()
}
