# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' grep column names matching a pattern across a list of dataframes
#'
#' @param df_list named list of dataframes to scan
#' @param pattern character string or regex pattern to search for
#' @param ignore_case logical. whether the search should be case-insensitive
#'
#' @returns a named list showing only the matched column names for each dataframe
#' @export
grep_columns_in_list <- function(df_list, pattern, ignore_case = TRUE) {
  
  # verify the incoming object is structurally a list format
  if (!is.list(df_list)) {
    stop("the input df_list must be a valid list object")
  }
  
  # ensure all list elements have tracking names assigned
  if (is.null(names(df_list))) {
    names(df_list) <- paste0("df_", seq_along(df_list))
  }
  
  # map across the list to extract matching column labels
  matched_results <- purrr::map(df_list, function(df) {
    
    # pull all column elements present in the data frame boundary matrix
    all_cols <- names(df)
    
    # run regular expression filter against the column metadata layer
    matching_cols <- stringr::str_subset(
      all_cols, 
      pattern = stringr::regex(pattern, ignore_case = ignore_case)
    )
    
    # return the matches if found, otherwise return null
    if (length(matching_cols) > 0) {
      return(matching_cols)
    } else {
      return(NULL)
    }
  })
  
  # compact down the list results to drop elements with zero matches
  purrr::compact(matched_results)
}
