# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' convert and label an excel export using xlsform workbook sheets
#'
#' @param data_df data.frame. the raw exported kobo data with label headers (df)
#' @param xlsform_path character. path to your local xlsform .xlsx workbook
#'
#' @returns a clean data frame with code headers and labeled categorical values
#' @export
label_with_xlsform <- function(data_df, xlsform_path) {
  
  # 1. read the design sheets from the xlsform template
  survey_sheet  <- readxl::read_excel(xlsform_path, sheet = "survey")
  choices_sheet <- readxl::read_excel(xlsform_path, sheet = "choices")
  
  # 2. handle column header conversion (label string -> code name)
  # ensure we only target actual question rows with values
  survey_clean <- survey_sheet %>%
    dplyr::filter(!is.na(name), !is.na(label)) %>%
    dplyr::mutate(clean_label = janitor::make_clean_names(label))
  
  # generate a named mapping dictionary vector: c(clean_label = "name")
  header_dict <- survey_clean %>%
    dplyr::select(clean_label, name) %>%
    dplyr::distinct(clean_label, .keep_all = TRUE) %>%
    tibble::deframe()
  
  current_names <- names(data_df)
  new_names <- sapply(current_names, function(col_name) {
    # check for a direct match
    if (col_name %in% names(header_dict)) {
      return(header_dict[[col_name]])
    }
    
    # check for select_multiple split columns
    # loops through labels to find if col_name starts with a known stem label
    matches <- sapply(names(header_dict), function(lbl) stringr::str_starts(col_name, fixed(lbl)))
    if (any(matches)) {
      best_fit_lbl <- names(which(matches))[which.max(nchar(names(which(matches))))]
      base_code_name <- header_dict[[best_fit_lbl]]
      
      # isolate the text choice suffix and append it back to the clean code stem
      suffix <- stringr::str_remove(col_name, paste0("^", gsub("([.[{}()^*+?|\\^$])", "\\\\\\1", best_fit_lbl), "_?"))
      return(paste0(base_code_name, "_", suffix))
    }
    return(col_name)
  })
  
  names(data_df) <- unname(new_names)
  
  # 3. handle categorical row value labeling
  # extract the choice list links from the question types (e.g., 'select_one list_name')
  questions_with_choices <- survey_clean %>%
    dplyr::filter(stringr::str_detect(type, "select_")) %>%
    dplyr::mutate(
      list_name = stringr::str_extract(type, "(?<=select_[a-zA-Z0-9_]{1,100}[:space:]).*")
    ) %>%
    dplyr::filter(!is.na(list_name)) %>%
    dplyr::select(name, list_name)
  
  # build dictionaries for each choice group inside the choices sheet
  choices_clean <- choices_sheet %>%
    dplyr::filter(!is.na(list_name), !is.na(name), !is.na(label)) %>%
    dplyr::mutate(
      name = as.character(name),
      lookup_key = paste0(list_name, "__", name)
    )
  
  choices_lookup <- choices_clean %>%
    dplyr::select(lookup_key, label) %>%
    dplyr::distinct(lookup_key, .keep_all = TRUE) %>%
    tibble::deframe()
  
  # create a question-to-list mapping vector
  q_to_list <- questions_with_choices %>% tibble::deframe()
  
  # 4. map row values across matching select columns
  data_df <- data_df %>%
    dplyr::mutate(dplyr::across(dplyr::everything(), function(col) {
      col_name <- dplyr::cur_column()
      
      if (col_name %in% names(q_to_list)) {
        list_name <- q_to_list[[col_name]]
        col_str <- as.character(col)
        
        # construct lookup codes: listname__value
        lookup_keys <- paste0(list_name, "__", col_str)
        
        col_mapped <- dplyr::if_else(
          lookup_keys %in% names(choices_lookup),
          choices_lookup[lookup_keys],
          col_str
        )
        return(col_mapped)
      }
      return(col)
    }))
  
  # universal pass to remove group dot leftovers if present
  data_df <- data_df %>%
    dplyr::rename_with(~ stringr::str_replace_all(.x, "\\.", "_"))
  
  return(data_df)
}
