# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Filter and Match Payroll Records Against Registration Data by County
#'
#' @description
#' Subsets registration data for a specific county, removes duplicate IDs,
#' joins the results with payroll records, and flags rows where the payroll name
#' is a partial match inside the registration name string.
#'
#' @param registration A data frame containing the primary registration benchmark records.
#' @param payroll A data frame containing the target payroll records to verify.
#' @param county_name Character string specifying the county name to filter on. Defaults to "Tana".
#'
#' @return A data frame matching the layout of the payroll dataset, appended with 
#'   columns from the subsetted registration data and a logical `names_match` flag.
#'
#' @importFrom dplyr filter select distinct left_join mutate
#' @importFrom stringi stri_detect_fixed
#'
#' @export
match_county_records <- function(registration, payroll, county_name = "Tana") {
  # filter registration pool for the target county and drop duplicate id records
  df_county_ref <- registration %>%
    dplyr::filter(grepl(county_name, county, ignore.case = TRUE)) %>%
    dplyr::select(ben_name, reg_num, ben_id_number) %>%
    dplyr::distinct(ben_id_number, .keep_all = TRUE)
  
  # merge payroll records with the clean county reference subset
  df_joined <- payroll %>%
    dplyr::left_join(
      df_county_ref,
      by = c("id_number" = "ben_id_number")
    ) %>%
    # remove residual system export columns starting with x or X
    dplyr::select(-grep("^[xX]", names(.)))
  
  # fast vectorized string detection — no r loops or nested scans
  df_joined %>%
    dplyr::mutate(
      names_match = !is.na(name_payroll) & 
        !is.na(ben_name) & 
        name_payroll != "" & 
        stringi::stri_detect_fixed(ben_name, name_payroll, case_insensitive = TRUE)
    )
}
