# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Normalize a Name Vector
#'
#' @description
#' Cleans a character vector of names by collapsing extra whitespace,
#' trimming leading/trailing spaces, and converting to title case.
#'
#' @param x A character vector of names.
#'
#' @return A cleaned character vector.
#'
#' @importFrom stringr str_squish str_to_title
#'
#' @export
#' @examples
#' \dontrun{normalize_names()}
normalize_names <- function(x) {
  x <- stringr::str_squish(x)       # trims + collapses internal spaces
  x <- stringr::str_to_title(x)     # title case
  x
}
