# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Parse and extract household size as an integer vector
#'
#' This function sanitizes a character vector of household sizes containing
#' mixed entries (e.g., "5(3F:2M)", "Size 9", "s6"), discarding data entry 
#' noise like phone numbers, registration IDs, or full names.
#'
#' @param x character. A vector containing raw household size values.
#'
#' @returns An integer vector of clean household sizes.
#' @export
#'
#' @examples
#' \dontrun{
#' clean_sizes <- parse_hhsize(df$ben_hhsize)
#' }
parse_hhsize <- function(x) {
  
  # convert vector to character and make uniform for regex matching
  working_vec <- stringr::str_trim(as.character(x))
  working_vec <- stringr::str_to_lower(working_vec)
  
  # perform structural parsing based on prioritized text patterns
  clean_vec <- dplyr::case_when(
    # extract leading total digits before bracketed breakdowns: '5(3f:2m)' -> 5
    stringr::str_detect(working_vec, "^\\d+\\s*\\(") ~ 
      stringr::str_extract(working_vec, "^\\d+"),
    
    # isolate strings with descriptive prefix layout: 'size 9' or 'fs- 5' -> 9 or 5
    stringr::str_detect(working_vec, "^(size|fs|fs-|s)\\s*\\d+$") ~ 
      stringr::str_extract(working_vec, "\\d+"),
    
    # isolate strings with standalone gender suffix layout: '3m' or '6f' -> 3 or 6
    stringr::str_detect(working_vec, "^\\d+[mf]$") ~ 
      stringr::str_extract(working_vec, "^\\d+"),
    
    # safely convert known text noise, registration IDs, and phone numbers to NA
    stringr::str_detect(working_vec, "-|\\s[a-z]|^07") ~ NA_character_,
    
    # keep remaining clean structures intact
    TRUE ~ working_vec
  )
  
  # return final casted integer vector
  return(as.integer(clean_vec))
}
