# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' patchwork a list of plots with headers for sections arranged left to right with unified axes labels
#'
#' @param plot_list list of ggplot objects
#' @param section_headers character vector of headers to place above sections
#' @param plots_per_section integer number of plots that belong under each header
#' @param nrow integer number of rows for the internal plot grids, defaults to 1
#'
#' @returns a patchwork layout object
#' @importFrom patchwork wrap_elements wrap_plots plot_annotation
#' @importFrom ggplot2 labs theme element_text margin element_blank
#' @export
patchwork_grid <- function(plot_list, section_headers, plots_per_section = 1, nrow = 1) {
  
  # validate that we have enough headers for the plots provided
  num_sections <- ceiling(length(plot_list) / plots_per_section)
  if (length(section_headers) < num_sections) {
    stop("not enough section_headers provided for the number of plot groups")
  }
  
  # extract global axis labels from the first plot before stripping them
  global_x_lab <- plot_list[[1]]$labels$x
  global_y_lab <- plot_list[[1]]$labels$y
  
  # strip inner labels to prevent repeating clutter across the panels
  clean_plots <- lapply(plot_list, function(p) {
    p + ggplot2::labs(x = NULL, y = NULL)
  })
  
  wrapped_sections <- list()
  
  # process plots group by group to wrap them under a styled section header
  for (i in seq_len(num_sections)) {
    
    # isolate the subset of plots for the current section
    start_idx <- ((i - 1) * plots_per_section) + 1
    end_idx <- min(i * plots_per_section, length(clean_plots))
    sub_plots <- clean_plots[start_idx:end_idx]
    
    # assemble the sub-grid for this specific section arranged by row
    section_grid <- patchwork::wrap_plots(sub_plots, nrow = nrow)
    
    # wrap the sub-grid as an element and attach a clean overarching title
    wrapped_sections[[i]] <- patchwork::wrap_elements(panel = section_grid) +
      ggplot2::labs(title = section_headers[i]) +
      ggplot2::theme(
        plot.title = ggplot2::element_text(
          face = "bold", 
          size = 14, 
          color = "#231F20", 
          margin = ggplot2::margin(b = 10, t = 5)
        )
      )
  }
  
  # stitch all header-managed sections horizontally side-by-side
  final_layout <- patchwork::wrap_plots(wrapped_sections, nrow = 1) +
    patchwork::plot_annotation(
      caption = global_x_lab, # uses caption style at bottom for clean centered x-axis label alignment
      theme = ggplot2::theme(
        plot.caption = ggplot2::element_text(face = "bold", size = 12, color = "#231F20", hjust = 0.5, margin = ggplot2::margin(t = 10))
      )
    )
  
  return(final_layout)
}
