# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot household aggregation counts using unicode location pins with bold plotmath ggrepel label text callouts
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param group_by character administrative grouping scale choice, either 'ward' or 'county'
#' @param compass_pos character layout position for the north arrow, defaults to 'bl'
#' @param font_size numeric. font size for labels
#'
#' @returns a ggplot object
#' @importFrom dplyr filter group_by summarise n count left_join mutate
#' @importFrom sf st_as_sf st_join st_centroid st_coordinates st_drop_geometry
#' @importFrom geodata gadm
#' @importFrom ggspatial annotation_north_arrow north_arrow_minimal
#' @importFrom ggrepel geom_text_repel
#' @importFrom grid arrow unit
#' @importFrom ggplot2 ggplot geom_sf geom_text aes labs theme_minimal theme element_text coord_sf element_rect
#' @export
plot_household_counts <- function(data, lat_col, lon_col, group_by = "ward", compass_pos = "bl", font_size = 2.8) {
  
  # isolate coordinates and filter out missing records
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]]))
  
  # transform the raw dataframe into a coordinate spatial sf object (wgs84 projection)
  sf_df <- sf::st_as_sf(
    plot_df, 
    coords = c(lon_col, lat_col), 
    crs = 4326
  )
  
  # dynamically download the official boundaries from gadm database
  kenya_spatvector_l1 <- geodata::gadm(country = "KEN", level = 1, path = base::tempdir())
  kenya_counties_sf <- sf::st_as_sf(kenya_spatvector_l1)
  
  kenya_spatvector_l3 <- geodata::gadm(country = "KEN", level = 3, path = base::tempdir())
  kenya_wards_sf <- sf::st_as_sf(kenya_spatvector_l3)
  
  # aggregate counts and build mathematical bold display labels based on chosen administrative group scale
  if (group_by == "ward") {
    # spatially join household coordinates to identify active ward parents
    sf_joined <- suppressMessages(sf::st_join(sf_df, kenya_wards_sf, join = sf::st_intersects))
    
    # generate frequencies matching unique gadm layer identifiers and drop point geometry structures safely
    counts_df <- sf_joined %>%
      sf::st_drop_geometry() %>%
      dplyr::filter(!is.na(GID_3)) %>%
      dplyr::count(GID_3, name = "hh_count")
    
    # bind counts back onto geometry frame and format text explicitly inside plotmath expressions
    annotated_sf <- kenya_wards_sf %>%
      dplyr::left_join(counts_df, by = "GID_3") %>%
      dplyr::filter(!is.na(hh_count)) %>%
      dplyr::mutate(display_label = base::paste0("atop(bold('", NAME_3, "'), '(N = ", hh_count, ")')"))
    
  } else if (group_by == "county") {
    # spatially join household coordinates to identify active county parents
    sf_joined <- suppressMessages(sf::st_join(sf_df, kenya_counties_sf, join = sf::st_intersects))
    
    # generate frequencies matching unique gadm layer identifiers and drop point geometry structures safely
    counts_df <- sf_joined %>%
      sf::st_drop_geometry() %>%
      dplyr::filter(!is.na(GID_1)) %>%
      dplyr::count(GID_1, name = "hh_count")
    
    # bind counts back onto geometry frame and format text explicitly inside plotmath expressions
    annotated_sf <- kenya_counties_sf %>%
      dplyr::left_join(counts_df, by = "GID_1") %>%
      dplyr::filter(!is.na(hh_count)) %>%
      dplyr::mutate(display_label = base::paste0("atop(bold('", NAME_1, "'), '(N = ", hh_count, ")')"))
  } else {
    base::stop("invalid group_by selection, please configure as either 'ward' or 'county'")
  }
  
  # extract geographic interior centroids calculated from the largest continuous landmass polygon space
  label_points <- base::suppressWarnings(sf::st_centroid(annotated_sf, of_largest_polygon = TRUE))
  label_coords <- sf::st_coordinates(label_points)
  
  annotated_sf$label_lon <- label_coords[, 1]
  annotated_sf$label_lat <- label_coords[, 2]
  
  # map the underlying geographic map framework and lay labels over top
  p <- ggplot2::ggplot() +
    # render detailed ward lines using thin soft pink profiles
    ggplot2::geom_sf(
      data = kenya_wards_sf,
      fill = "#fff5f6",
      color = "#FFE4E8",
      linewidth = 0.3,
      inherit.aes = FALSE
    ) +
    # overlay the main county line borders using a thicker soft pink profile
    ggplot2::geom_sf(
      data = kenya_counties_sf,
      fill = NA,
      color = "#FFB7C5",
      linewidth = 1.0,
      inherit.aes = FALSE
    ) +
    # drop authentic unicode location pin symbols directly locked onto the precise internal centroids
    ggplot2::geom_text(
      data = annotated_sf,
      ggplot2::aes(x = label_lon, y = label_lat),
      label = "\U0001F4CD",
      size = 5,
      vjust = 0.5
    ) +
    # repel text descriptions outside regional boundaries using mathematical parsing to force bold styling
    ggrepel::geom_text_repel(
      data = annotated_sf,
      ggplot2::aes(x = label_lon, y = label_lat, label = display_label),
      color = "#722F37",
      size = font_size,
      parse = TRUE,
      box.padding = 1.2,
      point.padding = 0.3,
      max.overlaps = Inf,
      arrow = grid::arrow(length = grid::unit(0.015, "npc"), type = "closed"),
      segment.color = "#722F37",
      segment.size = 0.4
    )
  
  # format layout grids and text descriptions
  p <- p +
    # enforce true spatial map coordinates and automatically scale map frame bounds to whole country shape
    ggplot2::coord_sf(crs = 4326) +
    # inject a minimal clean compass style north arrow matching the soft pink layout color at the custom location
    ggspatial::annotation_north_arrow(
      location = compass_pos, 
      which_north = "true",
      style = ggspatial::north_arrow_minimal(line_col = "#FFB7C5", fill = "#FFB7C5")
    ) +
    ggplot2::labs(
      x = "Longitude",
      y = "Latitude"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", hjust = 0.5, size = 13),
      legend.position = "bottom",
      legend.box = "vertical",
      # clean background panels
      panel.background = ggplot2::element_rect(fill = "#fff9fa", color = NA)
    )
  
  return(p)
}
