# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' visualize parts to whole using a donut layout framework
#'
#' @param data dataframe
#' @param fill_col character. the categorical column to slice
#' @param palette character vector. hex color values
#'
#' @returns a ggplot object
#' @importFrom dplyr count mutate across all_of
#' @importFrom ggplot2 ggplot aes geom_col geom_text scale_fill_manual theme_void theme coord_polar xlim position_stack
#' @importFrom scales percent
#' @export
#' @examples
#' \dontrun{plot_parts_donut()}
plot_parts_donut <- function(data, fill_col, palette = c("#81C784", "#FFB74D", "#E65100")) {
  
  # lower case comments without dots or dashes
  # map labels and compute dynamic cumulative coordinates for clean radial centering
  plot_df <- data %>%
    dplyr::count(dplyr::across(dplyr::all_of(fill_col))) %>%
    dplyr::mutate(
      pct = n / sum(n),
      pct_label = paste0(
        # .data[[fill_col]], 
        # "\n(", 
        scales::percent(pct, accuracy = 1)
        # ,")"
      )
    )
  
  ggplot2::ggplot(plot_df, ggplot2::aes(x = 3, y = pct, fill = .data[[fill_col]])) +
    # maintain stable donut ring layout thickness
    ggplot2::geom_col(width = 1, color = "white", size = 0.5) +
    # shift text position horizontally outward beyond the main donut frame
    ggplot2::geom_text(
      ggplot2::aes(x = 4.2, label = pct_label),
      position = ggplot2::position_stack(vjust = 0.5),
      color = "black",
      fontface = "bold",
      size = 3.5
    ) +
    ggplot2::scale_fill_manual(values = palette) +
    ggplot2::coord_polar(theta = "y") +
    # expand the coordinate map boundary to give labels complete breathing room
    ggplot2::xlim(c(1, 5.2)) +
    ggplot2::theme_void() +
    ggplot2::theme(
      legend.position = "bottom"
    )
}
