# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot interactive household count markers using real location pin icons positioned safely inside boundaries
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param group_by character administrative grouping scale choice, either 'ward' or 'county'
#' @param compass_pos character layout position for the north arrow, defaults to 'topleft'
#'
#' @returns a leaflet map widget object
#' @importFrom dplyr filter group_by summarise n count left_join mutate
#' @importFrom sf st_as_sf st_join st_point_on_surface st_coordinates st_drop_geometry
#' @importFrom geodata gadm
#' @importFrom leaflet leaflet addPolygons addMarkers labelOptions leafletOptions addControl
#' @importFrom htmltools HTML
#' @export
plot_household_counts_interactive <- function(data, lat_col, lon_col, group_by = "ward", compass_pos = "topleft") {
  
  # isolate coordinates and filter out missing records
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]]))
  
  # transform the raw dataframe into a coordinate spatial sf object (wgs84 projection)
  sf_df <- sf::st_as_sf(
    plot_df, 
    coords = c(lon_col, lat_col), 
    crs = 4326
  )
  
  # dynamically download the official boundaries from gadm database
  kenya_spatvector_l1 <- geodata::gadm(country = "KEN", level = 1, path = base::tempdir())
  kenya_counties_sf <- sf::st_as_sf(kenya_spatvector_l1)
  
  kenya_spatvector_l3 <- geodata::gadm(country = "KEN", level = 3, path = base::tempdir())
  kenya_wards_sf <- sf::st_as_sf(kenya_spatvector_l3)
  
  # aggregate counts and map tracking labels based on chosen administrative group scale
  if (group_by == "ward") {
    # spatially join household coordinates to identify active ward parents
    sf_joined <- base::suppressMessages(sf::st_join(sf_df, kenya_wards_sf, join = sf::st_intersects))
    
    # generate frequencies matching unique gadm layer identifiers and drop point geometry structures safely
    counts_df <- sf_joined %>%
      sf::st_drop_geometry() %>%
      dplyr::filter(!is.na(GID_3)) %>%
      dplyr::count(GID_3, name = "hh_count")
    
    # bind counts back onto geometry frame and format clean text combinations for interactive hover flags
    annotated_sf <- kenya_wards_sf %>%
      dplyr::left_join(counts_df, by = "GID_3") %>%
      dplyr::filter(!is.na(hh_count)) %>%
      dplyr::mutate(
        hover_label = base::paste0("<strong>Ward:</strong> ", NAME_3, "<br><strong>Households:</strong> ", hh_count)
      )
    
  } else if (group_by == "county") {
    # spatially join household coordinates to identify active county parents
    sf_joined <- base::suppressMessages(sf::st_join(sf_df, kenya_counties_sf, join = sf::st_intersects))
    
    # generate frequencies matching unique gadm layer identifiers and drop point geometry structures safely
    counts_df <- sf_joined %>%
      sf::st_drop_geometry() %>%
      dplyr::filter(!is.na(GID_1)) %>%
      dplyr::count(GID_1, name = "hh_count")
    
    # bind counts back onto geometry frame and format clean text combinations for interactive hover flags
    annotated_sf <- kenya_counties_sf %>%
      dplyr::left_join(counts_df, by = "GID_1") %>%
      dplyr::filter(!is.na(hh_count)) %>%
      dplyr::mutate(
        hover_label = base::paste0("<strong>County:</strong> ", NAME_1, "<br><strong>Households:</strong> ", hh_count)
      )
  } else {
    base::stop("invalid group_by selection, please configure as either 'ward' or 'county'")
  }
  
  # extract spatial surface coordinates guaranteed to be mathematically inside the polygon boundaries
  label_points <- base::suppressWarnings(sf::st_point_on_surface(annotated_sf))
  label_coords <- sf::st_coordinates(label_points)
  
  annotated_sf$label_lon <- label_coords[, 1]
  annotated_sf$label_lat <- label_coords[, 2]
  
  # design a custom html soft pink compass ornament using a safe portable unicode escape sequence for the arrow (\u25b2)
  compass_html <- htmltools::HTML('
    <div style="
      text-align: center; 
      font-family: sans-serif; 
      color: #FFB7C5; 
      background: rgba(255, 245, 246, 0.8); 
      padding: 6px 10px; 
      border-radius: 4px; 
      border: 2px solid #FFB7C5;
      font-weight: bold;
    ">
      <div style="font-size: 20px; line-height: 1;">\u25B2</div>
      <div style="font-size: 13px; margin-top: 2px;">N</div>
    </div>
  ')
  
  # initialize a clean leaflet map structure with zooming rules
  lf <- leaflet::leaflet(options = leaflet::leafletOptions(minZoom = 5, maxZoom = 14)) %>%
    # render detailed background ward lines using a very clean subtle light pink fill
    leaflet::addPolygons(
      data = kenya_wards_sf,
      fillColor = "#fffafb",
      fillOpacity = 0.6,
      color = "#FFE4E8",
      weight = 1,
      opacity = 0.8,
      group = "Wards"
    ) %>%
    # overlay the main county line borders using a thicker soft pink profile
    leaflet::addPolygons(
      data = kenya_counties_sf,
      fillColor = "transparent",
      color = "#FFB7C5",
      weight = 1.8,
      opacity = 1.0,
      group = "Counties"
    ) %>%
    # anchor the custom styled compass ornament securely to the canvas UI
    leaflet::addControl(html = compass_html, position = compass_pos) %>%
    # render native location pin icon markers that surface rich html label strings upon mouse hover
    leaflet::addMarkers(
      data = annotated_sf,
      lng = ~label_lon,
      lat = ~label_lat,
      label = ~base::lapply(hover_label, htmltools::HTML),
      labelOptions = leaflet::labelOptions(
        style = base::list(
          "font-family" = "sans-serif",
          "font-size" = "12px",
          "color" = "#722F37",
          "border-color" = "#FFB7C5"
        )
      )
    )
  
  return(lf)
}
