# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot bar graphs with automatic summary calculations
#'
#' @param data dataframe
#' @param x_var character vector x-axis variable
#' @param y_var character vector variable to calculate mean or proportion on
#' @param type character type of calculation: "count", "proportion", or "mean"
#' @param fill_col character vector of hex color code for fill
#' @param title character vector of title
#' @param subtitle character vector of subtitle
#' @param x_lab character vector of label for x-axis
#' @param y_lab character vector of label for y-axis
#' @importFrom rlang ensym as_label
#' @importFrom dplyr filter group_by summarize mutate ungroup
#' @importFrom ggplot2 ggplot aes geom_col geom_text labs scale_y_continuous scale_x_continuous expansion theme_minimal theme element_blank element_text
#' @importFrom scales percent comma
#'
#' @returns a ggplot object
#' @export
#'
#' @examples
#' \dontrun{plot_bar(data, x_var = "job_type", type = "count")}
plot_bar <- function(data, 
                     x_var, 
                     y_var = NULL, 
                     type = c("count", "proportion", "mean"),
                     fill_col = "#0066A1",
                     title = "variable distribution", 
                     subtitle = NULL, 
                     x_lab = NULL, 
                     y_lab = NULL) {
  
  type <- match.arg(type)
  x_sym <- rlang::ensym(x_var)
  x_char <- rlang::as_label(x_sym)
  
  # drop missing values from the grouping variable upfront
  data <- data %>% dplyr::filter(!is.na(!!x_sym))
  
  # standardizing labels based on the calculation metric
  if (is.null(y_lab)) {
    y_lab <- switch(type,
                    "count" = "count",
                    "proportion" = "proportion",
                    "mean" = "mean")
  }
  
  # internal data processing engine
  if (!is.null(y_var)) {
    y_sym <- rlang::ensym(y_var)
    
    if (type == "mean") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(metric = round(mean(!!y_sym, na.rm = TRUE)), .groups = "drop") %>%
        dplyr::filter(!is.na(metric))
      
    } else if (type == "proportion") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(
          metric = if (is.numeric(!!y_sym) || is.logical(!!y_sym)) {
            mean(!!y_sym == 1, na.rm = TRUE)
          } else {
            mean(!is.na(!!y_sym), na.rm = TRUE)
          }, 
          .groups = "drop"
        ) %>%
        dplyr::filter(!is.na(metric))
      
    } else if (type == "count") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(metric = sum(!!y_sym, na.rm = TRUE), .groups = "drop") %>%
        dplyr::mutate(pct = metric / sum(metric, na.rm = TRUE)) %>%
        dplyr::filter(!is.na(metric))
    }
    
  } else {
    summary_df <- data %>%
      dplyr::count(!!x_sym) %>%
      dplyr::mutate(pct = n / sum(n))
    
    # standardize name column for plotting step below
    summary_df$metric <- if (type == "proportion") summary_df$pct else summary_df$n
  }
  
  # force x to a standard factor to catch clean label text representations
  # lower case comments without dots
  summary_df$plot_x_factor <- as.factor(summary_df[[x_char]])
  x_labels <- levels(summary_df$plot_x_factor)
  
  # map numeric vectors to prevent single category blowout stretching
  summary_df$plot_x_numeric <- as.numeric(summary_df$plot_x_factor)
  
  # compile base plot with fixed coordinate controls and width reduced by another quarter
  p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = plot_x_numeric, y = metric)) +
    ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.225)
  
  # apply text label geometry based on metric configuration
  if (type == "proportion" || (is.null(y_var) && type == "proportion")) {
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = scales::percent(metric, accuracy = 0.1)),
      vjust = -0.5, size = 3, fontface = "bold"
    )
  } else if (type == "mean") {
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = scales::comma(metric, accuracy = 0.01)),
      vjust = -0.5, size = 3, fontface = "bold"
    )
  } else {
    p <- p + ggplot2::geom_text(
      ggplot2::aes(label = paste0(scales::comma(metric), " (", scales::percent(pct, accuracy = 0.1), ")")),
      vjust = -0.5, size = 3, fontface = "bold"
    )
  }
  
  # chart polishing and design options
  p <- p +
    ggplot2::labs(
      title = title,
      subtitle = subtitle,
      x = if(is.null(x_lab)) x_char else x_lab,
      y = y_lab
    ) +
    ggplot2::scale_x_continuous(
      breaks = 1:length(x_labels),
      labels = x_labels,
      limits = c(0.5, length(x_labels) + 0.5)
    ) +
    ggplot2::scale_y_continuous(labels = scales::comma, expand = ggplot2::expansion(mult = c(0, 0.2))) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 14, color = "#231F20"),
      plot.subtitle = ggplot2::element_text(size = 11, color = "#58595B"),
      axis.title = ggplot2::element_text(face = "bold", color = "#231F20"),
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, color = "#231F20"),
      axis.text.y = ggplot2::element_text(color = "#231F20")
    )
  
  return(p)
}
