# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' generate an interactive leaflet map of household clusters
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param village_col character name of the village column
#' @param county_col character optional name of the county column
#'
#' @returns a leaflet map object
#' @importFrom dplyr filter group_by across all_of summarise n ungroup
#' @importFrom leaflet leaflet addProviderTiles addCircleMarkers colorFactor addLegend providers labelOptions
#' @importFrom htmltools HTML
#' @export
plot_household_leaflet <- function(data, lat_col, lon_col, village_col, county_col = NULL) {
  
  # build grouping vector based on inputs
  group_vars <- village_col
  if (!is.null(county_col)) {
    group_vars <- c(county_col, group_vars)
  }
  
  # aggregate household coordinates to village level centers and counts
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]])) %>%
    dplyr::group_by(dplyr::across(dplyr::all_of(group_vars))) %>%
    dplyr::summarise(
      mean_lon = mean(.data[[lon_col]], na.rm = TRUE),
      mean_lat = mean(.data[[lat_col]], na.rm = TRUE),
      household_count = dplyr::n(),
      .groups = "drop"
    )
  
  # map values to a color column explicitly before entering leaflet
  if (!is.null(county_col)) {
    pal <- leaflet::colorFactor(palette = "viridis", domain = plot_df[[county_col]])
    plot_df$calculated_color <- pal(plot_df[[county_col]])
  } else {
    plot_df$calculated_color <- "#0073C2"
  }
  
  # configure mathematical radius translation in pixel limits
  max_count <- max(plot_df$household_count, na.rm = TRUE)
  min_count <- min(plot_df$household_count, na.rm = TRUE)
  
  get_radius <- function(count) {
    if (max_count == min_count) return(8)
    5 + 25 * (count - min_count) / (max_count - min_count)
  }
  
  # compile clean html strings for hover map popups
  labels <- sprintf(
    "<strong>Village:</strong> %s<br/><strong>Households:</strong> %d",
    plot_df[[village_col]],
    plot_df$household_count
  )
  if (!is.null(county_col)) {
    labels <- sprintf("<strong>County:</strong> %s<br/>%s", plot_df[[county_col]], labels)
  }
  html_labels <- lapply(labels, htmltools::HTML)
  
  # construct interactive spatial visualization canvas
  map <- leaflet::leaflet(plot_df) %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    leaflet::addCircleMarkers(
      lng = ~mean_lon,
      lat = ~mean_lat,
      radius = ~get_radius(household_count),
      color = ~calculated_color,
      stroke = TRUE,
      weight = 1,
      fillOpacity = 0.6,
      label = html_labels,
      labelOptions = leaflet::labelOptions(
        style = list("font-weight" = "normal", padding = "4px 8px"),
        textsize = "13px",
        direction = "auto"
      )
    )
  
  # attach legend module if grouped by county layers
  if (!is.null(county_col)) {
    map <- map %>%
      leaflet::addLegend(
        pal = pal,
        values = plot_df[[county_col]],
        opacity = 0.7,
        title = "County",
        position = "bottomright"
      )
  }
  
  return(map)
}

#' validate and recode household disability flags based on repeat group ages
#'
#' @param df_out dataframe containing the main household data
#' @param df_disab dataframe containing the individual repeat group data
#' @param uuid_col character string of the ID column name in df_out (defaults to "uuid")
#'
#' @returns an updated version of df_out with corrected disability flags
#'
#' @export
#'
#' @examples
#' # lower case comments without dots or dashes
#' # create dummy main dataset
#' main_df <- data.frame(
#'   uuid = c("hh_1", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "yes", "no"),
#'   stringsAsFactors = FALSE
#' )
#'
#' # create dummy repeat group dataset
#' repeat_df <- data.frame(
#'   `_uuid` = c("hh_1", "hh_1", "hh_2", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "no", "yes", "yes", "no"),
#'   prot_disability_ind_age = c(1, 35, 2, 1, 40),
#'   stringsAsFactors = FALSE,
#'   check.names = FALSE
#' )
#'
#' # run the function
#' output_df <- check_disability(main_df, repeat_df, uuid_col = "uuid")
check_disability <- function(df_out, df_disab, uuid_col = "uuid") {
  
  # step 1: isolate active disability rows and find the maximum age per household
  hh_max_disab_age <- df_disab %>%
    dplyr::filter(stringr::str_detect(base::tolower(HHM_disability), "yes")) %>%
    dplyr::group_by(`_uuid`) %>%
    dplyr::summarise(
      max_age = base::max(prot_disability_ind_age, na.rm = TRUE),
      .groups = "drop"
    )
  
  # step 2: extract household IDs where the maximum disabled age is 2 or under
  infant_only_uuids <- hh_max_disab_age %>%
    dplyr::filter(max_age <= 2) %>%
    dplyr::pull(`_uuid`)
  
  # step 3: calculate diagnostics for console visibility
  total_infant_only_hh <- base::length(infant_only_uuids)
  
  # step 4: recode the main dataset if any invalid target households exist
  df_out_updated <- df_out %>%
    dplyr::mutate(
      # lower case comments without dots or dashes
      HHM_disability = dplyr::if_else(
        .data[[uuid_col]] %in% infant_only_uuids,
        "no",
        HHM_disability
      )
    )
  
  # step 5: print diagnostic feedback to the console safely
  base::message("--- disability check summary ---")
  base::message(base::sprintf("households with active disability loops: %d", base::nrow(hh_max_disab_age)))
  base::message(base::sprintf("households where all disabled members are <= 2: %d", total_infant_only_hh))
  
  if (total_infant_only_hh > 0) {
    base::message("action: invalid household flags successfully recoded to 'no'")
  } else {
    base::message("action: no adjustments needed, all household flags are structurally valid")
  }
  base::message("--------------------------------")
  
  return(df_out_updated)
}
