# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot bar graphs
#'
#' @param data dataframe
#' @param x_var character vector x-axis variable
#' @param y_var character vector y-axis variable
#' @param fill_col character vector of hex color code for fill
#' @param title character vector of title
#' @param subtitle character vector of subtitle
#' @param x_lab character vector of label for x-axis
#' @param y_lab character vector of label for y-axis
#' @importFrom rlang ensym
#'
#' @returns list of plot object
#' @export
#'
#' @examples
#' \dontrun{plot_bar()}
plot_bar <- function(data, 
                     x_var, 
                     y_var = NULL, 
                     fill_col = "#0066A1",
                     title = "variable distribution", 
                     subtitle = NULL, 
                     x_lab = NULL, 
                     y_lab = "count") {
  
  x_sym <- rlang::ensym(x_var)
  
  if (!is.null(y_var)) {
    y_sym <- ensym(y_var)
    
    # case 1: plotting pre-calculated values with percent
    # we calculate total sum to derive percentages for the labels
    total_sum <- sum(data[[as_label(y_sym)]], na.rm = TRUE)
    
    # p <- ggplot(data, aes(x = fct_reorder(as.factor(!!x_sym), !!y_sym), y = !!y_sym)) +
    p <- ggplot2::ggplot(data, aes(x = !!x_sym, y = !!y_sym)) +
      ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
      ggplot2::geom_text(
        ggplot2::aes(label = paste0(!!y_sym, " (", scales::percent(!!y_sym / total_sum, accuracy = 0.1), ")")),
        vjust = -0.5, size = 3, fontface = "bold"
      )
    
  } else {
    # case 2: plotting frequencies with dynamic percent
    # p <- ggplot(data, aes(x = fct_infreq(as.factor(!!x_sym)))) +
    p <- ggplot2::ggplot(data, aes(x = !!x_sym)) +
      ggplot2::geom_bar(fill = fill_col, alpha = 0.9, width = 0.75) +
      ggplot2::geom_text(
        stat = "count",
        ggplot2::aes(label = after_stat(paste0(count, " (", scales::percent(count / sum(count), accuracy = 0.1), ")"))),
        vjust = -0.5, size = 3, fontface = "bold"
      )
  }
  
  p <- p +
    ggplot2::labs(
      title = title,
      subtitle = subtitle,
      x = if(is.null(x_lab)) as_label(x_sym) else x_lab,
      y = y_lab
    ) +
    # expand y axis further to accommodate longer labels
    ggplot2::scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(face = "bold", size = 14, color = "#231F20"),
      plot.subtitle = element_text(size = 11, color = "#58595B"),
      axis.title = element_text(face = "bold", color = "#231F20"),
      axis.text.x = element_text(angle = 45, hjust = 1, color = "#231F20"),
      axis.text.y = element_text(color = "#231F20")
    )
  
  return(p)
}
