# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' visualize parts to whole using an automated faceted donut grid via patchwork
#'
#' @param data dataframe
#' @param fill_col character. the categorical variable to slice (e.g. "FCSGName")
#' @param facet_col character. the variable to split panels by (e.g. "county")
#' @param palette character vector. hex color values mapping to categories
#'
#' @returns a patchwork grid assembly of donut plots
#' @importFrom dplyr filter count mutate pull
#' @importFrom ggplot2 ggplot aes geom_col geom_text scale_fill_manual theme_void theme coord_polar xlim labs element_text position_stack
#' @importFrom patchwork wrap_plots
#' @importFrom stringr str_to_title
#' @export
#' @examples
#' \dontrun{plot_faceted_donuts()}
plot_faceted_donuts <- function(data, 
                                fill_col, 
                                facet_col, 
                                palette = c("#388E3C", "#F57C00", "#D32F2F")) {
  
  # lower case comments without dots or dashes
  # extract unique facet groups while ignoring missing rows
  facet_groups <- data %>%
    dplyr::filter(!is.na(.data[[facet_col]])) %>%
    dplyr::pull(.data[[facet_col]]) %>%
    unique() %>%
    sort()
  
  # dynamically determine optimal column layouts based on category lengths
  n_facets <- length(facet_groups)
  calculated_ncol <- if (n_facets <= 3) {
    n_facets
  } else if (n_facets == 4) {
    2
  } else {
    3
  }
  
  # generate individual donut objects iteratively
  plot_list <- lapply(facet_groups, function(group) {
    
    # filter down to single panel subset
    sub_df <- data %>% 
      dplyr::filter(.data[[facet_col]] == group, !is.na(.data[[fill_col]]))
    
    # safeguard against empty group metrics
    if (nrow(sub_df) == 0) return(NULL)
    
    plot_df <- sub_df %>%
      dplyr::count(dplyr::across(dplyr::all_of(fill_col))) %>%
      dplyr::mutate(
        pct = n / sum(n),
        pct_label = paste0(
          .data[[fill_col]], 
          "\n(", 
          scales::percent(pct, accuracy = 1), 
          ")"
        )
      )
    
    ggplot2::ggplot(plot_df, ggplot2::aes(x = 3, y = pct, fill = .data[[fill_col]])) +
      # maintain donut thickness between radius limits 2 and 3.5
      ggplot2::geom_col(width = 1, color = "white", size = 0.5) +
      # push text radius position out beyond the chart area boundary
      ggplot2::geom_text(
        ggplot2::aes(x = 4.2, label = pct_label),
        position = ggplot2::position_stack(vjust = 0.5),
        color = "black",
        fontface = "bold",
        size = 2.8
      ) +
      ggplot2::scale_fill_manual(values = palette) +
      ggplot2::coord_polar(theta = "y") +
      # expand structural coordinate canvas limits to prevent text clipping
      ggplot2::xlim(c(1, 5.2)) +
      ggplot2::labs(title = stringr::str_to_title(group)) +
      ggplot2::theme_void() +
      ggplot2::theme(
        legend.position = "none",
        plot.title = ggplot2::element_text(hjust = 0.5, face = "bold", size = 11, vjust = -1)
      )
  })
  
  # drop null items from tracking list
  # using base r filter option to keep namespaces minimal
  plot_list <- plot_list[!sapply(plot_list, is.null)]
  
  # stitch panels together cleanly using automated column configurations
  combined_grid <- patchwork::wrap_plots(plot_list, ncol = calculated_ncol)
  
  return(combined_grid)
}
