# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' generate an interactive leaflet map of household clusters
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param village_col character name of the village column
#' @param county_col character optional name of the county column
#'
#' @returns a leaflet map object
#' @importFrom dplyr filter group_by across all_of summarise n ungroup
#' @importFrom leaflet leaflet addProviderTiles addCircleMarkers colorFactor addLegend providers labelOptions
#' @importFrom htmltools HTML
#' @export
plot_household_leaflet <- function(data, lat_col, lon_col, village_col, county_col = NULL) {
  
  # build grouping vector based on inputs
  group_vars <- village_col
  if (!is.null(county_col)) {
    group_vars <- c(county_col, group_vars)
  }
  
  # aggregate household coordinates to village level centers and counts
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]])) %>%
    dplyr::group_by(dplyr::across(dplyr::all_of(group_vars))) %>%
    dplyr::summarise(
      mean_lon = mean(.data[[lon_col]], na.rm = TRUE),
      mean_lat = mean(.data[[lat_col]], na.rm = TRUE),
      household_count = dplyr::n(),
      .groups = "drop"
    )
  
  # map values to a color column explicitly before entering leaflet
  if (!is.null(county_col)) {
    pal <- leaflet::colorFactor(palette = "viridis", domain = plot_df[[county_col]])
    plot_df$calculated_color <- pal(plot_df[[county_col]])
  } else {
    plot_df$calculated_color <- "#0073C2"
  }
  
  # configure mathematical radius translation in pixel limits
  max_count <- max(plot_df$household_count, na.rm = TRUE)
  min_count <- min(plot_df$household_count, na.rm = TRUE)
  
  get_radius <- function(count) {
    if (max_count == min_count) return(8)
    5 + 25 * (count - min_count) / (max_count - min_count)
  }
  
  # compile clean html strings for hover map popups
  labels <- sprintf(
    "<strong>Village:</strong> %s<br/><strong>Households:</strong> %d",
    plot_df[[village_col]],
    plot_df$household_count
  )
  if (!is.null(county_col)) {
    labels <- sprintf("<strong>County:</strong> %s<br/>%s", plot_df[[county_col]], labels)
  }
  html_labels <- lapply(labels, htmltools::HTML)
  
  # construct interactive spatial visualization canvas
  map <- leaflet::leaflet(plot_df) %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    leaflet::addCircleMarkers(
      lng = ~mean_lon,
      lat = ~mean_lat,
      radius = ~get_radius(household_count),
      color = ~calculated_color,
      stroke = TRUE,
      weight = 1,
      fillOpacity = 0.6,
      label = html_labels,
      labelOptions = leaflet::labelOptions(
        style = list("font-weight" = "normal", padding = "4px 8px"),
        textsize = "13px",
        direction = "auto"
      )
    )
  
  # attach legend module if grouped by county layers
  if (!is.null(county_col)) {
    map <- map %>%
      leaflet::addLegend(
        pal = pal,
        values = plot_df[[county_col]],
        opacity = 0.7,
        title = "County",
        position = "bottomright"
      )
  }
  
  return(map)
}
