# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot individual household coordinates over all kenya county borders with a compass arrow
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param county_col character optional name of the county column for coloring
#'
#' @returns a ggplot object
#' @importFrom dplyr filter
#' @importFrom sf st_as_sf
#' @importFrom geodata gadm
#' @importFrom ggspatial annotation_north_arrow north_arrow_minimal
#' @importFrom ggplot2 ggplot aes geom_sf scale_color_viridis_d labs theme_minimal theme element_text coord_sf element_rect
#' @importFrom stringr str_to_title
#' @export
plot_household <- function(data, lat_col, lon_col, county_col = NULL) {
  
  # isolate coordinates and filter out missing records
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]]))
  
  # explicitly drop any unused factor levels for active counties in household dataset
  if (!is.null(county_col)) {
    plot_df[[county_col]] <- base::droplevels(base::as.factor(plot_df[[county_col]]))
  }
  
  # transform the raw dataframe into a coordinate spatial sf object (wgs84 projection)
  sf_df <- sf::st_as_sf(
    plot_df, 
    coords = c(lon_col, lat_col), 
    crs = 4326
  )
  
  # dynamically download the official 47 kenya county boundaries (level 1) from gadm database
  kenya_spatvector <- geodata::gadm(country = "KEN", level = 1, path = base::tempdir())
  
  # convert the SpatVector format cleanly into a native sf collection for ggplot pipelines
  kenya_counties_sf <- sf::st_as_sf(kenya_spatvector)
  
  # map the underlying geographic map framework and lay points over top
  p <- ggplot2::ggplot() +
    # render all 47 kenya county lines with a thick sweet soft pink boundary line (#ffb7c5)
    ggplot2::geom_sf(
      data = kenya_counties_sf,
      fill = "#fff5f6",
      color = "#FFB7C5",
      linewidth = 1.0,
      inherit.aes = FALSE
    )
  
  # apply color grouping if a county column is provided using low alpha to reveal overplotting
  if (!is.null(county_col)) {
    p <- p + 
      ggplot2::geom_sf(
        data = sf_df, 
        ggplot2::aes(color = .data[[county_col]]), 
        size = 1.5,
        alpha = 0.25,
        inherit.aes = FALSE
      ) +
      ggplot2::scale_color_viridis_d(option = "plasma", end = 0.85, drop = TRUE)
  } else {
    p <- p + 
      ggplot2::geom_sf(
        data = sf_df, 
        color = "#0073C2", 
        size = 1.5,
        alpha = 0.25,
        inherit.aes = FALSE
      )
  }
  
  # format layout grids and text descriptions
  p <- p +
    # enforce true spatial map coordinates and automatically scale map frame bounds to whole country shape
    ggplot2::coord_sf(crs = 4326) +
    # inject a minimal clean compass style north arrow matching the soft pink layout color
    ggspatial::annotation_north_arrow(
      location = "tr", 
      which_north = "true",
      style = ggspatial::north_arrow_minimal(line_col = "#FFB7C5", fill = "#FFB7C5")
    ) +
    ggplot2::labs(
      x = "Longitude",
      y = "Latitude",
      color = stringr::str_to_title(county_col)
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", hjust = 0.5, size = 13),
      legend.position = "bottom",
      legend.box = "vertical",
      # clean background panels
      panel.background = ggplot2::element_rect(fill = "#fff9fa", color = NA)
    )
  
  return(p)
}

