# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot interactive household coordinates over all kenya county borders for shiny layouts with a compass rose
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param county_col character optional name of the county column for coloring
#'
#' @returns a leaflet map widget object
#' @importFrom dplyr filter
#' @importFrom sf st_as_sf
#' @importFrom geodata gadm
#' @importFrom leaflet leaflet addPolygons addCircleMarkers leafletOptions addControl
#' @importFrom htmltools HTML
#' @importFrom scales viridis_pal
#' @export
plot_household_interactive <- function(data, lat_col, lon_col, county_col = NULL) {
  
  # isolate coordinates and filter out missing records
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]]))
  
  # explicitly drop any unused factor levels for active counties in household dataset
  if (!is.null(county_col)) {
    plot_df[[county_col]] <- base::droplevels(base::as.factor(plot_df[[county_col]]))
  }
  
  # transform the raw dataframe into a coordinate spatial sf object (wgs84 projection)
  sf_df <- sf::st_as_sf(
    plot_df, 
    coords = c(lon_col, lat_col), 
    crs = 4326
  )
  
  # dynamically download the official 47 kenya county boundaries (level 1) from gadm database
  kenya_spatvector <- geodata::gadm(country = "KEN", level = 1, path = base::tempdir())
  kenya_counties_sf <- sf::st_as_sf(kenya_spatvector)
  
  # design a custom html soft pink compass ornament using a safe portable unicode escape sequence for the arrow (\u25b2)
  compass_html <- htmltools::HTML('
    <div style="
      text-align: center; 
      font-family: sans-serif; 
      color: #FFB7C5; 
      background: rgba(255, 245, 246, 0.8); 
      padding: 6px 10px; 
      border-radius: 4px; 
      border: 2px solid #FFB7C5;
      font-weight: bold;
    ">
      <div style="font-size: 20px; line-height: 1;">\u25B2</div>
      <div style="font-size: 13px; margin-top: 2px;">N</div>
    </div>
  ')
  
  # initialize a clean leaflet map structure with zooming rules
  lf <- leaflet::leaflet(options = leaflet::leafletOptions(minZoom = 5, maxZoom = 14)) %>%
    # render all 47 kenya county lines with a sweet soft pink boundary line (#ffb7c5)
    leaflet::addPolygons(
      data = kenya_counties_sf,
      fillColor = "#fff5f6",
      fillOpacity = 0.4,
      color = "#FFB7C5",
      weight = 2,
      opacity = 1.0,
      label = ~NAME_1,
      highlightOptions = leaflet::highlightOptions(
        weight = 3,
        color = "#722F37",
        bringToFront = FALSE
      )
    ) %>%
    # anchor the custom styled compass ornament securely to the top-right corner
    leaflet::addControl(html = compass_html, position = "topright")
  
  # apply interactive points using variable color maps if a county column is provided
  if (!is.null(county_col)) {
    # generate matching color engine for explicit column groupings
    pal <- leaflet::colorFactor(
      palette = scales::viridis_pal(option = "plasma", end = 0.85)(100),
      domain = sf_df[[county_col]]
    )
    
    lf <- lf %>%
      leaflet::addCircleMarkers(
        data = sf_df,
        color = ~pal(sf_df[[county_col]]),
        radius = 4,
        stroke = FALSE,
        fillOpacity = 0.25,
        label = ~base::paste0("County: ", sf_df[[county_col]])
      )
  } else {
    lf <- lf %>%
      leaflet::addCircleMarkers(
        data = sf_df,
        color = "#0073C2",
        radius = 4,
        stroke = FALSE,
        fillOpacity = 0.25
      )
  }
  
  return(lf)
}

#' validate and recode household disability flags based on repeat group ages
#'
#' @param df_out dataframe containing the main household data
#' @param df_disab dataframe containing the individual repeat group data
#' @param uuid_col character string of the ID column name in df_out (defaults to "uuid")
#'
#' @returns an updated version of df_out with corrected disability flags
#'
#' @export
#'
#' @examples
#' # lower case comments without dots or dashes
#' # create dummy main dataset
#' main_df <- data.frame(
#'   uuid = c("hh_1", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "yes", "no"),
#'   stringsAsFactors = FALSE
#' )
#'
#' # create dummy repeat group dataset
#' repeat_df <- data.frame(
#'   `_uuid` = c("hh_1", "hh_1", "hh_2", "hh_2", "hh_3"),
#'   HHM_disability = c("yes", "no", "yes", "yes", "no"),
#'   prot_disability_ind_age = c(1, 35, 2, 1, 40),
#'   stringsAsFactors = FALSE,
#'   check.names = FALSE
#' )
#'
#' # run the function
#' output_df <- check_disability(main_df, repeat_df, uuid_col = "uuid")
check_disability <- function(df_out, df_disab, uuid_col = "uuid") {
  
  # step 1: isolate active disability rows and find the maximum age per household
  hh_max_disab_age <- df_disab %>%
    dplyr::filter(stringr::str_detect(base::tolower(HHM_disability), "yes")) %>%
    dplyr::group_by(`_uuid`) %>%
    dplyr::summarise(
      max_age = base::max(prot_disability_ind_age, na.rm = TRUE),
      .groups = "drop"
    )
  
  # step 2: extract household IDs where the maximum disabled age is 2 or under
  infant_only_uuids <- hh_max_disab_age %>%
    dplyr::filter(max_age <= 2) %>%
    dplyr::pull(`_uuid`)
  
  # step 3: calculate diagnostics for console visibility
  total_infant_only_hh <- base::length(infant_only_uuids)
  
  # step 4: recode the main dataset if any invalid target households exist
  df_out_updated <- df_out %>%
    dplyr::mutate(
      # lower case comments without dots or dashes
      HHM_disability = dplyr::if_else(
        .data[[uuid_col]] %in% infant_only_uuids,
        "no",
        HHM_disability
      )
    )
  
  # step 5: print diagnostic feedback to the console safely
  base::message("--- disability check summary ---")
  base::message(base::sprintf("households with active disability loops: %d", base::nrow(hh_max_disab_age)))
  base::message(base::sprintf("households where all disabled members are <= 2: %d", total_infant_only_hh))
  
  if (total_infant_only_hh > 0) {
    base::message("action: invalid household flags successfully recoded to 'no'")
  } else {
    base::message("action: no adjustments needed, all household flags are structurally valid")
  }
  base::message("--------------------------------")
  
  return(df_out_updated)
}
