# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot household density by clustering household level coordinates into villages
#'
#' @param data dataframe containing household level records
#' @param lat_col character name of the latitude column
#' @param lon_col character name of the longitude column
#' @param village_col character name of the village column to group by
#' @param county_col character optional name of the county column for coloring
#'
#' @returns a ggplot object
#' @importFrom dplyr filter group_by across all_of summarise n ungroup
#' @importFrom ggplot2 ggplot aes geom_point coord_equal scale_size_continuous scale_color_viridis_d labs theme_minimal theme element_text
#' @importFrom stringr str_to_title
#' @export
plot_household <- function(data, lat_col, lon_col, village_col, county_col = NULL) {
  
  # build grouping vector based on inputs
  group_vars <- village_col
  if (!is.null(county_col)) {
    group_vars <- c(county_col, group_vars)
  }
  
  # aggregate household coordinates to village level centers and counts
  plot_df <- data %>%
    dplyr::filter(!is.na(.data[[lat_col]]), !is.na(.data[[lon_col]])) %>%
    dplyr::group_by(dplyr::across(dplyr::all_of(group_vars))) %>%
    dplyr::summarise(
      mean_lon = mean(.data[[lon_col]], na.rm = TRUE),
      mean_lat = mean(.data[[lat_col]], na.rm = TRUE),
      household_count = dplyr::n(),
      .groups = "drop"
    )
  
  # map the village center coordinates and bind size to household counts
  p <- ggplot2::ggplot(
    plot_df, 
    ggplot2::aes(
      x = mean_lon, 
      y = mean_lat, 
      size = household_count
    )
  )
  
  # apply color grouping if a county column is provided
  if (!is.null(county_col)) {
    p <- p + ggplot2::geom_point(ggplot2::aes(color = .data[[county_col]]), alpha = 0.7) +
      ggplot2::scale_color_viridis_d(option = "plasma", end = 0.85)
  } else {
    p <- p + ggplot2::geom_point(color = "#0073C2", alpha = 0.6)
  }
  
  # format layout grids and text descriptions
  p <- p +
    # enforce equal aspect ratio so kenya geography looks correct
    ggplot2::coord_equal() +
    # scale bubble sizes dynamically so larger villages pop out
    ggplot2::scale_size_continuous(range = c(3, 15)) +
    ggplot2::labs(
      x = "Longitude",
      y = "Latitude",
      size = "Households per Village",
      color = stringr::str_to_title(county_col)
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", hjust = 0.5, size = 13),
      legend.position = "bottom",
      legend.box = "vertical"
    )
  
  return(p)
}
