# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot bar graphs for top n frequencies
#'
#' @param data dataframe
#' @param x_var character vector x-axis variable
#' @param y_var character vector variable to calculate mean or proportion on
#' @param type character type of calculation: "count", "proportion", or "mean"
#' @param n_top integer maximum number of highest value categories to display
#' @param fill_col character vector of hex color code for fill
#' @param title character vector of title
#' @param subtitle character vector of subtitle
#' @param x_lab character vector of label for x-axis
#' @param y_lab character vector of label for y-axis
#' @importFrom rlang ensym as_label
#' @importFrom tidyr separate_rows
#' @importFrom dplyr filter group_by summarize mutate slice_max ungroup desc
#' @importFrom ggplot2 ggplot aes geom_col geom_text labs scale_y_continuous scale_x_discrete expansion theme_minimal theme element_blank element_text
#' @importFrom scales percent comma
#' @importFrom forcats fct_reorder
#'
#' @returns a ggplot object
#' @export
#'
#' @examples
#' \dontrun{plot_bar_top_n(data, x_var = "job_type", type = "count", n_top = 10)}
plot_bar_top_n <- function(data, 
                           x_var, 
                           y_var = NULL, 
                           type = c("count", "proportion", "mean"),
                           n_top = 10,
                           fill_col = "#0066A1",
                           title = "top variable distribution", 
                           subtitle = NULL, 
                           x_lab = NULL, 
                           y_lab = NULL) {
  
  type <- match.arg(type)
  x_sym <- rlang::ensym(x_var)
  x_char <- rlang::as_label(x_sym)
  
  # auto expand multiple response space separated text strings if present
  # if (is.character(data[[x_char]])) {
  #   data <- data %>% tidyr::separate_rows(!!x_sym, sep = " ")
  # }
  # 
  # drop missing values from the grouping variable
  data <- data %>% dplyr::filter(!is.na(!!x_sym))
  
  # standardizing labels based on the calculation metric
  if (is.null(y_lab)) {
    y_lab <- switch(type,
                    "count" = "count",
                    "proportion" = "proportion",
                    "mean" = "mean")
  }
  
  # internal data processing engine
  if (!is.null(y_var)) {
    y_sym <- rlang::ensym(y_var)
    
    if (type == "mean") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(metric = round(mean(!!y_sym, na.rm = TRUE)), .groups = "drop") %>%
        dplyr::slice_max(order_by = metric, n = n_top, with_ties = FALSE)
      
      p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = forcats::fct_reorder(!!x_sym, dplyr::desc(metric)), y = metric)) +
        ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
        ggplot2::geom_text(
          ggplot2::aes(label = scales::comma(metric, accuracy = 0.01)),
          vjust = -0.5, size = 3, fontface = "bold"
        )
      
    } else if (type == "proportion") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(metric = mean(!!y_sym == 1, na.rm = TRUE), .groups = "drop") %>%
        dplyr::slice_max(order_by = metric, n = n_top, with_ties = FALSE)
      
      p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = forcats::fct_reorder(!!x_sym, dplyr::desc(metric)), y = metric)) +
        ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
        ggplot2::geom_text(
          ggplot2::aes(label = scales::percent(metric, accuracy = 0.1)),
          vjust = -0.5, size = 3, fontface = "bold"
        )
      
    } else if (type == "count") {
      summary_df <- data %>%
        dplyr::group_by(!!x_sym) %>%
        dplyr::summarize(metric = sum(!!y_sym, na.rm = TRUE), .groups = "drop") %>%
        dplyr::mutate(pct = metric / sum(metric, na.rm = TRUE)) %>%
        dplyr::slice_max(order_by = metric, n = n_top, with_ties = FALSE)
      
      p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = forcats::fct_reorder(!!x_sym, dplyr::desc(metric)), y = metric)) +
        ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
        ggplot2::geom_text(
          ggplot2::aes(label = paste0(scales::comma(metric), " (", scales::percent(pct, accuracy = 0.1), ")")),
          vjust = -0.5, size = 3, fontface = "bold"
        )
    }
    
  } else {
    # case when no y variable is supplied (calculating straight counts/proportions of rows)
    summary_df <- data %>%
      dplyr::count(!!x_sym) %>%
      dplyr::mutate(pct = n / sum(n)) %>%
      dplyr::slice_max(order_by = n, n = n_top, with_ties = FALSE)
    
    if (type == "proportion") {
      p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = forcats::fct_reorder(!!x_sym, dplyr::desc(pct)), y = pct)) +
        ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
        ggplot2::geom_text(
          ggplot2::aes(label = scales::percent(pct, accuracy = 0.1)),
          vjust = -0.5, size = 3, fontface = "bold"
        )
    } else {
      p <- ggplot2::ggplot(summary_df, ggplot2::aes(x = forcats::fct_reorder(!!x_sym, dplyr::desc(n)), y = n)) +
        ggplot2::geom_col(fill = fill_col, alpha = 0.9, width = 0.75) +
        ggplot2::geom_text(
          ggplot2::aes(label = paste0(scales::comma(n), " (", scales::percent(pct, accuracy = 0.1), ")")),
          vjust = -0.5, size = 3, fontface = "bold"
        )
    }
  }
  
  # chart polishing and design options
  p <- p +
    ggplot2::labs(
      title = title,
      subtitle = subtitle,
      x = if(is.null(x_lab)) x_char else x_lab,
      y = y_lab
    ) +
    ggplot2::scale_y_continuous(labels = scales::comma, expand = ggplot2::expansion(mult = c(0, 0.2))) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 14, color = "#231F20"),
      plot.subtitle = ggplot2::element_text(size = 11, color = "#58595B"),
      axis.title = ggplot2::element_text(face = "bold", color = "#231F20"),
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, color = "#231F20"),
      axis.text.y = ggplot2::element_text(color = "#231F20")
    )
  
  return(p)
}
