# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' plot age distribution faceted by gender using patchwork
#'
#' @param data dataframe containing household level records
#' @param age_group_col character name of the column containing age categories
#' @param gender_col character name of the gender column
#' @param fill_col hex code or color string for the bar fills
#'
#' @returns a patchwork layout object
#' @importFrom dplyr filter count group_by mutate ungroup
#' @importFrom ggplot2 ggplot aes geom_col geom_text scale_x_discrete coord_flip labs theme_minimal theme element_text element_blank scale_x_continuous
#' @importFrom patchwork wrap_plots
#' @importFrom rlang .data
#' @importFrom scales percent
#' @export
plot_age_gender <- function(data, age_group_col, gender_col, fill_col = "grey60") {
  
  # define unified categories to explicitly lock axis structure
  # lower case comments without dots
  age_cats <- sort(na.omit(unique(data[[age_group_col]])))
  
  # calculate percentages within each gender group and drop rows not in age cats
  plot_data <- data %>%
    dplyr::filter(.data[[age_group_col]] %in% age_cats) %>%
    dplyr::count(.data[[gender_col]], .data[[age_group_col]]) %>%
    dplyr::group_by(.data[[gender_col]]) %>%
    dplyr::mutate(pct = n / sum(n)) %>%
    dplyr::ungroup()
  
  # force explicit continuous mapping indices to block category layout stretching
  plot_data$age_factor <- factor(plot_data[[age_group_col]], levels = age_cats)
  plot_data$age_numeric <- as.numeric(plot_data$age_factor)
  
  # find male and female records using case insensitive pattern matching
  male_rows <- grepl("male", plot_data[[gender_col]], ignore.case = TRUE) & 
    !grepl("female", plot_data[[gender_col]], ignore.case = TRUE)
  female_rows <- grepl("female", plot_data[[gender_col]], ignore.case = TRUE)
  
  male_df <- plot_data[male_rows, ]
  female_df <- plot_data[female_rows, ]
  
  # build male plot with categories on the left edge using numeric spacing constraints
  p_male <- ggplot2::ggplot(male_df, ggplot2::aes(x = age_numeric, y = pct)) +
    ggplot2::geom_col(fill = fill_col, width = 0.225) +
    ggplot2::geom_text(
      ggplot2::aes(label = scales::percent(pct, accuracy = 1)),
      hjust = -0.2,
      size = 3.5
    ) +
    ggplot2::scale_x_continuous(
      breaks = 1:length(age_cats),
      labels = age_cats,
      limits = c(0.5, length(age_cats) + 0.5),
      position = "top"
    ) +
    ggplot2::coord_flip(clip = "off") +
    ggplot2::labs(x = NULL, y = "males") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_text(hjust = 0.5),
      axis.text.x = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    )
  
  # build female plot with hidden vertical axis text to prevent layout overlap
  p_female <- ggplot2::ggplot(female_df, ggplot2::aes(x = age_numeric, y = pct)) +
    ggplot2::geom_col(fill = fill_col, width = 0.225) +
    ggplot2::geom_text(
      ggplot2::aes(label = scales::percent(pct, accuracy = 1)),
      hjust = -0.2,
      size = 3.5
    ) +
    ggplot2::scale_x_continuous(
      breaks = 1:length(age_cats),
      labels = age_cats,
      limits = c(0.5, length(age_cats) + 0.5)
    ) +
    ggplot2::coord_flip(clip = "off") +
    ggplot2::labs(x = NULL, y = "females") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    )
  
  # stitch both plots together horizontally using patchwork
  final_plot <- patchwork::wrap_plots(p_male, p_female)
  
  return(final_plot)
}
