# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' preprocess unocha registrations
#'
#' @param df dataframe
#' @importFrom dm dm_flatten_to_tbl
#' @importFrom dplyr mutate group_by case_when if_else filter bind_rows distinct
#'
#' @returns a dataframe
#' @export
#'
#' @examples
#' \dontrun{preprocess_reg()}
#'
preprocess_reg <- function(df){
  df_out <- df %>% 
  dm_flatten_to_tbl(main)

df_out <- df_out %>%
  mutate(across(where(labelled::is.labelled), as.character))
df_out <- df_out %>%
  dplyr::mutate(
    village = case_when(
      grepl("chini", village, ignore.case = T) & grepl(
        "kalakacha", sublocation, ignore.case = T
      ) ~ "Kalakacha Chini",
      TRUE ~ village
    )
  )
df_out <- df_out %>%
  mutate(
    village = case_when(
      grepl("Emmaus|Kirengender", village, ignore.case = T) ~ "Kirengender",
      grepl("salama|Kajificheni", village, ignore.case = T) ~ "Salama",
      grepl("kalkacha_juu", village, ignore.case = T) ~ "Kalakacha Juu",
      TRUE ~ village
    )
#     troublesome
    ,
    enum_egency = case_when(
      grepl("mitobini", village, ignore.case = T) &
      grepl("pgi", enum_egency, ignore.case = T) ~ "ALDEF",
      # grepl("Milimani", village, ignore.case = T) & 
      #   date(start) >= date("2026-05-13") ~ "ALDEF",
      # grepl("kurole", village, ignore.case = T) ~ "ALDEF",
      grepl("elwachu", village, ignore.case = T) ~ "ALDEF",
      TRUE ~ enum_egency
    )
  )

df_out <- df_out %>% 
  dplyr::mutate(
    ben_first_surname = paste(first_name, third_name),
    ben_first_secname = paste(first_name, second_name)
  )

df_out <- df_out %>% 
  dplyr::mutate(
    HHH_age_calc = if_else(
      !is.na(resp_age), resp_age, HHH_age
    )
  )

df_out <- df_out %>% 
  mutate(
    county = gsub("_", " ", county)
  )
df_out <- df_out %>%
  dplyr::mutate(
    age_category = cut_numeric(HHH_age_calc),
    hh_size_category = cut_numeric(
      hh_size,
      breaks = c(1, 3, 6, 10, Inf),
      labels = c("1 - 2", "3 - 5", "6 - 9", ">= 10")
    ),
    hh_disabl_category = cut_numeric(
      hh_disability_count,
      breaks = c(0,1, 3, 5, Inf),
      labels = c("0", "1 - 2", "3 - 4", ">= 5")
    )
  )

  
df_out <- df_out %>%
  labelled::set_variable_labels(
    age_category = "Household\n Head Age",
    HHH_chronic = "HH Head\n Chronic illness",
    HHM_chronic = "HH Member\n Chronic illness",
    average_income = "Monthly Income",
    hh_size = "Household Size",
    hh_size_category = "Household Size",
    FCSGName = "Food Consumption\n Score",
    eligibility = "Eligibility",
    enum_egency = "Agency",
    enum_name = "Enumerator\n first name",
    first_name = "respondent\n first name",
    reg_num = "Respondent Phone",
    trust_proxy = "Trust proxy",
    enum_egency = "Partner",
    proxy_num_consent = "proxy consent",
    name_proxy_first = "proxy\n first name",
    proxy_num = "proxy mobile",
    proxy_relation = "proxy relation",
    HHM_disability = "Household\n disability",
    HHH_chronic = "Household\nchronic illness"
  )

# registration started May 3 ----------------------------------------------

df_out <- df_out %>% 
  dplyr::filter(
#     start of reg
    start >= lubridate::date("2026-05-03")
  ) %>%
  dplyr::filter(!(start < lubridate::date("2026-05-07") & grepl("SND", enum_egency))) 
  
  # distinct(
  #   ben_name, reg_num, ben_id_number, .keep_all = T
  # ) %>%
  # distinct(
  #   reg_num, ben_id_number, .keep_all = T
  # ) %>% 
  
# reg_num can be NA but distinct() would only pick one row

df_clean <- df_out %>%
  filter(is.na(reg_num)) %>%
  bind_rows(
    df_out %>%
      filter(!is.na(reg_num)) %>%
      distinct(reg_num, .keep_all = TRUE)
  ) %>%
  mutate(
    village = gsub("_", " ", village),
    county = gsub("_", " ", county)
  )

}
