# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean payroll data
#'
#' @param x dataframe
#'
#' @returns dataframe
#' @export
#'
process_payroll <- function(x) {
  # find columns matching pattern to pass safely to standard selectors
  drop_cols <- grep("^x", names(x), ignore.case = TRUE, value = TRUE)
  
  # target accounting columns requiring explicit type casting
  numeric_targets <- c(
    "cash_transfer_kes", 
    "mpesa_sending_charges", 
    "mpesa_withdrawal_charges", 
    "total_amount_kes"
  )
  
  x %>%
    # drops matching columns safely if they exist, ignores if empty
    dplyr::select(-dplyr::any_of(drop_cols)) %>%
    
    # defensive filter check: if "no" exists, filters out NAs; if missing, lets all rows pass
    dplyr::filter(dplyr::if_any(dplyr::any_of("no"), ~ !is.na(.x)) | !("no" %in% names(.))) %>%
    
    # defensive mutate check: targets telephone_number safely using any_of
    dplyr::mutate(
      # dplyr::across(
      #   dplyr::any_of("telephone_number"),
      #   ~ gsub("^254", "0", as.character(.x))
      # ),
      # defensive numeric conversion check: loops through specified financial column keys if present
      dplyr::across(
        dplyr::any_of(numeric_targets),
        ~ as.numeric(.x)
      )
    ) %>%
    mutate(
      across(
        any_of(c("name_of_beneficiary", "name_of_proxy", "telephone_number", "id_number")),
        clean_username
      )
    ) %>% clean_phone_number()
}
