# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' pull data from any kobo API project and align structures dynamically
#'
#' @param url character. Kobotoolbox url
#' @param project_id character. project id
#' @param token character. project token
#'
#' @returns a clean dataframe matching manual excel column conventions universally
#' @export
pull_kobo_data <- function(
    url = Sys.getenv("kobo_url"),
    project_id = Sys.getenv("unocha_id"),
    token = Sys.getenv("unocha_token")
){
  
  robotoolbox::kobo_setup(url = url, token = token)
  
  # pull all data rows and historical columns
  df <- robotoolbox::kobo_data(project_id, all_versions = TRUE)
  
  # force convert metadata levels into plain text strings safely
  df <- df %>%
    dplyr::mutate(dplyr::across(dplyr::everything(), function(col) {
      lbls <- attr(col, "labels")
      if (!is.null(lbls)) {
        lookup <- names(lbls)
        names(lookup) <- as.character(lbls)
        col_str <- as.character(col)
        
        return(dplyr::if_else(col_str %in% names(lookup), lookup[col_str], col_str))
      }
      return(col)
    }))
  
  # 1. drop the plain 'uuid' column first to prevent naming collisions
  df <- df %>%
    dplyr::select(-dplyr::any_of("uuid"))
  
  # 2. rename standard system fields to match manual clean excel structures
  df <- df %>%
    dplyr::rename(
      id = dplyr::any_of("_id"),
      uuid = dplyr::any_of("_uuid"),
      status = dplyr::any_of("_status"),
      submission_time = dplyr::any_of("_submission_time"),
      validation_status = dplyr::any_of("_validation_status"),
      submitted_by = dplyr::any_of("_submitted_by"),
      version = dplyr::any_of("__version__"),
      meta_root_uuid = dplyr::any_of("rootUuid")
    ) %>%
    # project agnostic: converts ALL group delimiter dots to underscores
    # handles patterns like 'a.sec_cluster' -> 'a_sec_cluster' or 'b.age' -> 'b_age'
    dplyr::rename_with(~ stringr::str_replace_all(.x, "\\.", "_"))
  
  # 3. drop general platform-specific headers not in standard clean excel exports
  df <- df %>%
    dplyr::select(
      -dplyr::any_of(c(
        "_attachments",
        "_xform_id_string",
        "instanceID",
        "instanceName",
        "cordinates_latitude",
        "cordinates_longitude",
        "cordinates_altitude",
        "cordinates_precision",
        "index",
        "tags",
        "notes"
      ))
    )
  
  return(df)
}
