# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' pull data from kobo API
#'
#' @param url character. Kobotoolbox url
#' @param project_id character. project id
#' @param token character. project token
#'
#' @returns a list
#' @export
#'
#' @examples
#' \dontrun{pull_kobo_data()}
pull_kobo_data <- function(
    url = Sys.getenv("kobo_url"),
    project_id = Sys.getenv("unocha_id"),
    token = Sys.getenv("unocha_token")
    
){
  
  robotoolbox::kobo_setup(url = url, token = token)
  
  df <- robotoolbox::kobo_data(project_id)
  return(df)
}
