# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Read multiple Excel sheets into a list or data frame with clean names
#'
#' @description
#' Iterates through available worksheets within an Excel file, extracts 
#' their content into a structured list, and standardizes column names using snake_case. 
#' If the file contains exactly one worksheet, it automatically drops the list format 
#' and returns a single data frame directly.
#'
#' @param path Character string representing the path to the Excel file.
#' @param bind_rows Logical indicator. If TRUE, binds multiple extracted sheets into 
#'   a single unified data frame using a compiler identifier column. Defaults to FALSE.
#' @param id Character string naming the optional identifier column that tracks 
#'   the source sheet name when `bind_rows` is TRUE. Defaults to "sheet_name".
#'
#' @return A single data frame if only one sheet exists or `bind_rows = TRUE`. 
#'   Otherwise, a named list of data frames representing individual sheets.
#'
#' @importFrom readxl excel_sheets read_excel
#' @importFrom purrr set_names map list_rbind
#' @importFrom janitor clean_names
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # if file has 1 sheet, returns a data frame directly; if multiple, returns a list
#' output_data <- read_excel_sheets("survey_data.xlsx", bind_rows = FALSE)
#' }
read_workbook <- function(path, bind_rows = FALSE, id = "sheet_name") {
  
  # identify all available worksheet names within the workbook
  sheet_names <- readxl::excel_sheets(path)
  
  # short circuit and return a single data frame instantly if only one sheet is found
  if (length(sheet_names) == 1) {
    single_df <- readxl::read_excel(path = path, sheet = sheet_names) %>%
      janitor::clean_names()
    return(single_df)
  }
  
  # extract sheet names, read contents, and standardize variables to snake case
  sheets_list <- sheet_names %>%
    purrr::set_names() %>%
    purrr::map(~ {
      readxl::read_excel(path = path, sheet = .x) %>%
        janitor::clean_names()
    })
  
  # conditionally collapse the list rows into a single data frame if specified
  if (bind_rows) {
    # names_to maps list names cleanly onto the bound frame rows
    combined_data <- purrr::list_rbind(sheets_list, names_to = id)
    return(combined_data)
  }
  
  return(sheets_list)
}
