# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Read Excel sheets or an entire workbook into a list or data frame with clean names
#'
#' @description
#' Iterates through available worksheets within an Excel file or targets a specific sheet, 
#' extracts content while skipping a designated number of rows, and standardizes column names 
#' using snake_case. If the target evaluation resolves to exactly one worksheet, it automatically 
#' drops the list format and returns a single data frame directly.
#'
#' @param path Character string representing the path to the Excel file.
#' @param bind_rows Logical indicator. If TRUE, binds multiple extracted sheets into 
#'   a single unified data frame using a compiler identifier column. Defaults to FALSE.
#' @param id Character string naming the optional identifier column that tracks 
#'   the source sheet name when `bind_rows` is TRUE. Defaults to "sheet_name".
#' @param skip Integer specifying the number of rows to skip at the start of reading. Defaults to 0.
#' @param sheet_name Character string specifying a single sheet to read. If NULL, all sheets are processed. Defaults to NULL.
#'
#' @return A single data frame if only one sheet is processed or `bind_rows = TRUE`. 
#'   Otherwise, a named list of data frames representing individual sheets.
#'
#' @importFrom readxl excel_sheets read_excel
#' @importFrom purrr set_names map list_rbind
#' @importFrom janitor clean_names
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # read a specific sheet and skip the first 2 rows
#' df_raw <- read_workbook("survey_data.xlsx", sheet_name = "Main_Data", skip = 2)
#' }
read_workbook <- function(path, bind_rows = FALSE, id = "sheet_name", skip = 0, sheet_name = NULL) {
  
  # determine target sheet names based on user input selection
  if (!is.null(sheet_name)) {
    sheet_names <- sheet_name
  } else {
    sheet_names <- readxl::excel_sheets(path)
  }
  
  # short circuit and return a single data frame instantly if only one sheet is target evaluated
  if (length(sheet_names) == 1) {
    single_df <- readxl::read_excel(path = path, sheet = sheet_names, skip = skip) %>%
      janitor::clean_names()
    return(single_df)
  }
  
  # extract sheet names, read contents, and standardize variables to snake case
  sheets_list <- sheet_names %>%
    purrr::set_names() %>%
    purrr::map(~ {
      readxl::read_excel(path = path, sheet = .x, skip = skip) %>%
        janitor::clean_names()
    })
  
  # conditionally collapse the list rows into a single data frame if specified
  if (bind_rows) {
    combined_data <- purrr::list_rbind(sheets_list, names_to = id)
    return(combined_data)
  }
  
  return(sheets_list)
}
