# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' read an xlsform file and compile it into a kobo asset metadata list
#'
#' @param xlsform_path character. path to your local xlsform .xlsx or .xls file
#'
#' @returns a named list structured exactly like a robotoolbox kobo_asset object
#' @importFrom readxl read_excel
#' @importFrom dplyr filter select
#' @export
read_xlsform_asset <- function(xlsform_path) {
  
  # 1. read the survey design sheet from the workbook
  survey_sheet <- readxl::read_excel(xlsform_path, sheet = "survey")
  
  # 2. filter down to rows that represent real questions with names
  survey_questions <- survey_sheet %>%
    dplyr::filter(!is.na(name))
  
  # 3. isolate all available label columns (handles multilingual headers like label::English (en))
  label_cols <- names(survey_questions)[stringr::str_starts(names(survey_questions), "label")]
  
  # if no complex language markers exist, default back to standard label
  if (length(label_cols) == 0 && "label" %in% names(survey_questions)) {
    label_cols <- "label"
  }
  
  # 4. dynamically build the mocked asset list structure
  kobo_asset <- list()
  
  for (i in seq_len(nrow(survey_questions))) {
    col_name <- survey_questions$name[i]
    
    # gather all label strings for the current question row
    labels_vec <- c()
    for (lbl_col in label_cols) {
      lbl_val <- survey_questions[[lbl_col]][i]
      
      if (!is.na(lbl_val) && lbl_val != "") {
        # normalize name format: strip 'label::' prefix if present to isolate language key
        lang_key <- stringr::str_remove(lbl_col, "^label::")
        if (lang_key == "label") lang_key <- "default"
        
        labels_vec[lang_key] <- lbl_val
      }
    }
    
    # structure each element as an empty mock column container holding label metadata
    col_trigger <- list()
    attr(col_trigger, "label") <- labels_vec
    
    kobo_asset[[col_name]] <- col_trigger
  }
  
  return(kobo_asset)
}
