# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' recode factors to character
#'
#' @param x dataframe
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{recode_factor_to_character(df)}
recode_factor_to_character <- function(x) {
  x %>%
  dplyr::mutate(
    dplyr::across(
      dplyr::where(labelled::is.labelled),
      # capture variable label and strip only value labels to protect raw values
      ~ {
        var_lbl <- attr(.x, "label")
        
        # remove value labels to safely retain raw characters like kakuma or daadab
        # lower case comments without dots or dashes
        res <- .x %>%
          labelled::remove_val_labels() %>%
          as.character()
        
        if (!is.null(var_lbl)) {
          attr(res, "label") <- var_lbl
        }
        
        res
      }
    )
  )
}
