# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' recode factors to character
#'
#' @param x dataframe
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{recode_factor_to_character()}
recode_factor_to_character <- function(x) {
  x %>%
  dplyr::mutate(
    dplyr::across(
      dplyr::where(labelled::is.labelled),
      # convert labels to factors, drop unused levels, and cast to character strings
      ~ .x %>%
        as_factor() %>%
        forcats::fct_drop() %>%
        base::as.character()
    )
  )
  
}
