# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' reset disability columns based on age thresholds
#'
#' @param data dataframe containing the disability and age columns
#' @param disability_cols character vector of column names representing the domains
#' @param age_col character name of the column storing age values
#'
#' @returns a modified dataframe with recoded disability entries for children under 6
#' @export
recode_early_childhood_disability <- function(data,
                                              disability_cols = c(
                                                "level_seeing_disability",
                                                "level_hearing_disability",
                                                "level_selfcare_disability",
                                                "level_remembering_disability",
                                                "level_walking_disability",
                                                "level_communicating_disability"
                                              ),
                                              age_col = "prot_disability_ind_age") {
  data %>%
    dplyr::mutate(
      dplyr::across(
        dplyr::all_of(disability_cols),
        ~ dplyr::if_else(
          # check if age exists and falls below the 6 year target threshold
          !is.na(.data[[age_col]]) & .data[[age_col]] < 6,
          "No difficulty",
          # preserve the original cell contents if criteria are not met
          as.character(.x)
        )
      )
    )
}
