# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' save a list of active plots into a grid using the png device
#'
#' @param plot_list list of ggplot or grid objects
#' @param output_path character path where the combined grid will be saved
#' @param ncol integer number of columns in the grid
#' @param width integer width of output image in pixels
#' @param height integer height of output image in pixels
#' @param res integer nominal resolution in ppi
#'
#' @return invisible null saves file directly to disk
#' @importFrom grDevices png dev.off
#' @importFrom grid grid.newpage pushViewport viewport grid.layout
#' @export
save_plots_to_png <- function(plot_list, 
                                   output_path, 
                                   ncol = 2, 
                                   width = 1600, 
                                   height = 1200, 
                                   res = 144) {
  
  # calculate layout grid dimensions based on total plot count
  n_plots <- length(plot_list)
  nrow <- ceiling(n_plots / ncol)
  
  # open the native png graphics device to catch the upcoming draw calls
  grDevices::png(
    filename = output_path, 
    width = width, 
    height = height, 
    res = res
  )
  
  # initialize a fresh blank grid canvas page
  grid::grid.newpage()
  
  # push the base grid layout matrix structure onto the canvas
  grid::pushViewport(
    grid::viewport(layout = grid::grid.layout(nrow, ncol))
  )
  
  # loop through every plot object in the list and assign coordinates
  for (i in seq_along(plot_list)) {
    row_idx <- ceiling(i / ncol)
    col_idx <- (i - 1) %% ncol + 1
    
    # render the plot directly into its designated grid cell coordinates
    print(
      plot_list[[i]], 
      vp = grid::viewport(layout.pos.row = row_idx, layout.pos.col = col_idx)
    )
  }
  
  # shut down the active device to commit and write the file to disk
  grDevices::dev.off()
}
