# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' slice registration to match starting dates
#'
#' @param df dataframe
#'
#' @returns dataframe
#' @export
#'
#' @examples
#' \dontrun{slice_reg()}
slice_reg <- function(df){
  df_out <- df %>% 
  dplyr::filter(
#     start of reg
    start >= lubridate::date("2026-05-03")
  ) %>%
  dplyr::filter(
    !(
    lubridate::as_date(start) <= lubridate::date("2026-05-06") & 
    grepl("SND", enum_egency, ignore.case = TRUE)
  )
  )
  df_out
}
