# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Map and Standardize Administrative Names to Reference Values
#'
#' This function takes a dataset containing entered administrative names (such as
#' sublocations or villages) and cross-references them against an official lookup
#' table. It matches names using an optimal string alignment distance algorithm
#' to automatically correct typos, casing differences, and minor variations.
#'
#' @param data A data frame containing the main survey or household records.
#' @param match_col A bare or quoted column name in \code{data} containing the 
#'   entered names that need correction.
#' @param ref_df A data frame serving as the official reference lookup table.
#' @param ref_col A bare or quoted column name in \code{ref_df} containing the
#'   true, standardized reference names.
#' @param max_dist A numeric value specifying the maximum allowed string distance
#'   for a match to be considered valid. Greater values allow more generous 
#'   typo corrections. Defaults to \code{2}.
#'
#' @return A data frame with the same rows as \code{data}, where the original
#'   \code{match_col} values are replaced by the true values from \code{ref_col}.
#'   Unmatched records will retain their original values or return \code{NA} if 
#'   completely outside the distance threshold.
#'
#' @importFrom dplyr mutate row_number across any_of
#' @importFrom rlang .data
#' @importFrom stringdist amatch
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # dummy raw survey data with typos
#' survey_records <- data.frame(
#'   household_id = 1:4,
#'   entered_sublocation = c("Muguga ", "Kikuyu", "sigona", "UnknownPlace")
#' )
#'
#' # true official reference registry
#' official_sublocations <- data.frame(
#'   true_name = c("Muguga", "Kikuyu", "Sigona", "Karai")
#' )
#'
#' # clean and standardize the sublocation entries
#' cleaned_data <- standardize_names(
#'   data      = survey_records,
#'   match_col = "entered_sublocation",
#'   ref_df    = official_sublocations,
#'   ref_col   = "true_name",
#'   max_dist  = 3
#' )
#' }
standardize_names <- function(
    data,
    match_col,
    ref_df,
    ref_col,
    max_dist = 2
) {
  
  # convert input column names safely to standard strings
  match_str <- as.character(substitute(match_col))
  if (!match_str %in% names(data)) match_str <- match_col
  
  ref_str <- as.character(substitute(ref_col))
  if (!ref_str %in% names(ref_df)) ref_str <- ref_col
  
  # extract the target reference vector clean of missing entries
  ref_vector <- as.character(na.omit(ref_df[[ref_str]]))
  
  # extract and clean input entries for robust string matching
  raw_entries <- as.character(data[[match_str]])
  clean_raw   <- trimws(tolower(raw_entries))
  clean_ref   <- trimws(tolower(ref_vector))
  
  # find matching vector indices based on optimal string alignment distance
  match_indices <- stringdist::amatch(
    x          = clean_raw,
    table      = clean_ref,
    method     = "osa",
    maxDist    = max_dist
  )
  
  # map matched indices back to original true casing from reference list
  standardized_values <- ifelse(
    !is.na(match_indices),
    ref_vector[match_indices],
    raw_entries
  )
  
  # assign corrected values back to the original target column mask
  standardized_df <- data %>%
    dplyr::mutate(
      dplyr::across(
        dplyr::any_of(match_str),
        ~ standardized_values
      )
    )
  
  return(standardized_df)
}
