# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' publication ready theme wrapper using cowplot with gridlines
#'
#' @param base_size numeric base font size
#' @param base_family character font family
#'
#' @returns a ggplot2 theme object
#' @importFrom cowplot theme_minimal_grid
#' @importFrom ggplot2 theme element_text rel margin
#' @export
theme_plots <- function(base_size = 11, base_family = "sans") {
  
  # leverage cowplot minimal grid as the structural foundation
  cowplot::theme_minimal_grid(
    base_size = base_size,
    base_family = base_family,
    rel_title = 1.25
  ) +
    # fine tune alignment and margins
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold",
        hjust = 0.5,
        margin = ggplot2::margin(b = 10)
      ),
      plot.subtitle = ggplot2::element_text(
        hjust = 0.5,
        color = "grey30",
        face = "plain",
        margin = ggplot2::margin(b = 8)
      ),
      legend.position = "bottom"
    )
}
