# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' export a named list of data frames to an excel workbook
#' @param df_list a named list of data frames
#' @param file_path character string for the output path
#' @returns NULL
#' @export
#' @examples
#' \dontrun{write_list_to_excel()}
write_list_to_excel <- function(df_list, file_path) {
  
  # create a new workbook object
  wb <- openxlsx::createWorkbook()
  
  # define a professional header style
  header_style <- createStyle(
    fgFill = "#4F81BD", 
    halign = "center", 
    textDecoration = "bold",
    fontColour = "white",
    border = "bottom"
  )
  
  # iterate through the named list
  # .x is the dataframe, .y is the name of the list element
  purrr::iwalk(df_list, function(.x, .y) {
    
    # add a new worksheet with the name of the list element
    # excel sheet names are limited to 31 characters
    sheet_name <- substr(.y, 1, 31)
    openxlsx::addWorksheet(wb, sheet_name)
    
    # write the data to the sheet
    openxlsx::writeData(wb, sheet_name, .x, headerStyle = header_style)
    
    # adjust column widths to fit content automatically
    openxlsx::setColWidths(wb, sheet_name, cols = 1:ncol(.x), widths = "auto")
    
    # freeze the top row for easier navigation
    openxlsx::freezePane(wb, sheet_name, firstRow = TRUE)
  })
  
  # save the workbook to the specified path
  openxlsx::saveWorkbook(wb, file_path, overwrite = TRUE)
}
